export const articles = [
  { slug: "home-insurance-deductibles", title: "Understanding Home Insurance Deductibles", summary: "How all-peril, water, wind, and percentage deductibles can change your out-of-pocket cost.", body: ["A deductible is the portion of a covered loss you pay before policy benefits apply. Home policies can use a flat dollar amount, a percentage of the dwelling limit, or different deductibles for specific causes of loss.", "Compare more than the premium. A higher deductible may reduce cost, but it also increases what you must absorb after a claim. Confirm whether water, wind, wildfire, or other losses have separate deductibles.", "Choose an amount your household could comfortably pay after an unexpected loss, and review it whenever your dwelling limit changes."] },
  { slug: "fair-plan-dic", title: "California FAIR Plan and DIC Coverage Explained", summary: "Why two policies are often used together for homes in wildfire-exposed areas.", body: ["The California FAIR Plan is an insurer of last resort that generally provides basic fire coverage for eligible properties. It is not designed to replace a comprehensive homeowners policy.", "A Difference in Conditions policy may add coverages such as liability, theft, water damage, and loss of use, depending on its terms. The two policies must be reviewed together because limits, deductibles, and exclusions do not automatically align.", "Eligibility, underwriting, coverage, and pricing vary. Neither policy should be assumed active until binding is confirmed."] },
  { slug: "replacement-cost-market-value", title: "Replacement Cost vs. Market Value", summary: "Why the amount needed to rebuild a home is different from its sale price.", body: ["Market value reflects what a buyer may pay for the property, including land, location, and demand. Replacement cost estimates the labor and materials needed to rebuild the insured structure after a covered loss.", "A home can have a market value above or below its reconstruction cost. Insurance dwelling limits are generally based on reconstruction characteristics rather than the purchase price or loan balance.", "Review square footage, construction quality, attached structures, upgrades, and local rebuilding costs for accuracy."] },
  { slug: "insurance-before-escrow", title: "What Realtors Should Know About Insurance Before Escrow", summary: "Early insurance review can uncover wildfire, claims-history, roof, and occupancy concerns.", body: ["Insurance availability can affect affordability and closing timelines. Obtain a quote early, especially for older homes, wildfire-exposed areas, prior losses, unusual occupancy, or multiple structures.", "The carrier may need inspections, replacement-cost details, mortgagee information, or evidence of updates. Starting early gives buyers time to compare coverage without delaying loan documents.", "A quote is not proof of coverage. Confirm binding and lender-ready evidence before closing."] },
  { slug: "auto-garaging-address", title: "Why Your Auto Garaging Address Matters", summary: "Where a vehicle is regularly kept affects rating, eligibility, and accurate coverage.", body: ["The garaging address is where a vehicle is primarily kept, not necessarily the mailing address. Insurers use it to evaluate local traffic, theft, weather, and claim patterns.", "A move can change premium because the risk characteristics change. Household drivers and vehicle use must also be listed accurately.", "Report address changes promptly so underwriting and claims decisions are based on correct information."] },
  { slug: "gl-vs-workers-comp", title: "General Liability vs. Workers’ Compensation", summary: "These business policies protect against different types of loss.", body: ["General liability commonly addresses third-party bodily injury, property damage, and certain personal or advertising injury claims. Workers’ compensation addresses work-related employee injuries and occupational illness, subject to law and policy terms.", "One does not replace the other. Businesses should also review payroll, employee classifications, subcontractor exposure, and certificate requirements.", "Accurate classifications and payroll estimates help reduce surprises during a workers’ compensation audit."] },
  { slug: "premium-mortgage-escrow", title: "How Insurance Premiums Affect Mortgage Escrow", summary: "Understand annual premium, monthly escrow estimates, and changes after renewal.", body: ["When insurance is paid through escrow, the servicer generally collects part of the projected annual premium with each mortgage payment. Dividing the annual premium by 12 provides an estimate, but the servicer’s calculation may differ.", "A renewal increase or policy replacement can change the escrow analysis. Shortages, reserves, taxes, and timing can also affect the monthly payment.", "Send updated evidence and invoices to the lender promptly, and ask the servicer to explain its final escrow calculation."] },
  { slug: "umbrella-insurance", title: "Umbrella Insurance: When Additional Liability Protection Matters", summary: "Additional liability limits may help protect income and assets after a serious claim.", body: ["An umbrella policy can provide liability limits above eligible home and auto policies, subject to its terms and required underlying limits.", "It may be valuable for households with assets, future earnings, youthful drivers, rental property, frequent guests, or other elevated liability exposure.", "Review exclusions, underlying-policy requirements, covered household members, and all vehicles and properties before selecting a limit."] },
] as const;

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }
