export type GuideSection = { heading: string; paragraphs: string[] };
type Lesson = { sections: GuideSection[]; limits: string };
type BilingualLesson = { en: Lesson; es: Lesson; sources: { label: string; url: string }[] };
const residential = { label: "California Department of Insurance: residential insurance", url: "https://www.insurance.ca.gov/01-consumers/105-type/95-guides/03-res/res-ins-guide.cfm" };
const auto = { label: "California Department of Insurance: auto coverage explained", url: "https://www.insurance.ca.gov/01-consumers/105-type/95-guides/01-auto/auto101.cfm" };
const commercial = { label: "California Department of Insurance: commercial insurance", url: "https://www.insurance.ca.gov/01-consumers/105-type/95-guides/09-comm/commercialguide.cfm" };
const workers = { label: "California DWC: employer questions", url: "https://www.dir.ca.gov/dwc/faqs.html" };

// Paired teaching sections share one key so English and Spanish examples stay aligned.
// This is an editorial update date, not a claim of staff or legal review.
export const guideUpdated = "2026-09-07";
export const guideLessons: Record<string, BilingualLesson> = {
  "home-insurance-deductibles": {
    sources: [residential],
    en: { limits: "Compare the premium savings with the extra deductible you would have to fund. Convert any percentage deductible into dollars using the basis stated in your policy.", sections: [
      { heading: "What would you actually pay?", paragraphs: ["Illustrative example: a covered kitchen loss costs $12,000 to repair. With a $2,500 deductible, the simplified payment is $9,500. With a $5,000 deductible, it is $7,000. Both calculations assume sufficient coverage, one applicable deductible, and no depreciation, special limit, or other settlement adjustment.", "A percentage is different. If the policy uses 2% of a $600,000 dwelling limit, the deductible is $12,000—not 2% of the repair bill. A loss below that deductible produces no payment under that coverage."] },
      { heading: "Compare savings with cash you can access", paragraphs: ["Suppose the higher deductible saves an illustrative $250 a year but adds $2,500 to your share of a claim. Ten claim-free years would equal that extra exposure. That arithmetic is a comparison tool, not a prediction of when a loss will happen. Ask us to show each deductible beside the annual premium and identify any separate water or wildfire deductible before you choose."] },
    ] },
    es: { limits: "Compare el ahorro de prima con el deducible adicional que tendría que pagar. Convierta cualquier deducible porcentual a dólares usando la base indicada en su póliza.", sections: [
      { heading: "¿Cuánto pagaría de su bolsillo?", paragraphs: ["Ejemplo ilustrativo: reparar un daño cubierto en la cocina cuesta $12,000. Con un deducible de $2,500, el pago simplificado es $9,500. Con uno de $5,000, es $7,000. Ambos cálculos suponen cobertura suficiente, un solo deducible aplicable y ningún ajuste por depreciación, límite especial u otra condición de liquidación.", "Un porcentaje funciona de otra manera. Si la póliza usa el 2% de un límite de vivienda de $600,000, el deducible es $12,000, no el 2% de la reparación. Una pérdida inferior a ese deducible no genera un pago bajo esa cobertura."] },
      { heading: "Compare el ahorro con sus fondos disponibles", paragraphs: ["Supongamos que aumentar el deducible ahorra $250 al año, pero agrega $2,500 a su parte de un reclamo. Harían falta diez años sin reclamos para igualar esa exposición adicional. Son cifras ilustrativas para comparar, no una predicción. Pídanos mostrar cada deducible junto a la prima anual e identificar cualquier deducible separado por agua o incendio forestal antes de elegir."] },
    ] },
  },
  "fair-plan-dic": {
    sources: [{ label: "California FAIR Plan: dwelling coverage", url: "https://www.cfpnet.com/policies/dwelling/" }, { label: "California FAIR Plan: Difference in Conditions", url: "https://www.cfpnet.com/difference-in-conditions-dic/" }, residential],
    en: { limits: "Compare the combined annual cost of both policies, but review each policy's limits, exclusions, deductibles, dates, and claim-reporting instructions separately.", sections: [
      { heading: "Fire insurance is only one part of the picture", paragraphs: ["The FAIR Plan's dwelling policy covers named perils: only the causes of loss listed in the contract. Its basic listed causes include fire and lightning, internal explosion, and smoke; optional coverage such as vandalism costs extra. This is not a policy that automatically covers every kind of damage to a house.", "Difference in Conditions (DIC) is a companion policy purchased from another insurer, not from the FAIR Plan. In this setting it addresses non-fire protections such as theft, certain water damage, and personal liability. Liability means protection against covered claims that you are legally responsible for someone else's injury or property damage. The DIC contract determines the protections actually included."] },
      { heading: "Picture a fire, then a leaking pipe", paragraphs: ["Hypothetical example: a fire damages your roof. The FAIR Plan is the policy to examine for that fire loss. A separate event—a suddenly burst pipe damaging cabinets—calls for a review of the companion policy's water coverage. Long-term seepage, wear, or poor maintenance can fall outside that coverage. Two policies do not mean two payments for the same damage or that every gap disappears.", "Ask which policy pays for temporary housing after each type of loss. Additional living expense pays eligible increased living costs; fair rental value is a different benefit and should not be assumed to reimburse hotel bills. Also check building-code upgrades, belongings, and excluded flood and earthquake risks. Do not assume a FAIR Plan/DIC combination is identical to a standard homeowners policy."] },
      { heading: "Bring both documents to the same review", paragraphs: ["Have us compare the declarations pages—the summaries of insured people, property, dates, limits, and deductibles—plus the forms and endorsements that change coverage. Confirm matching effective dates, rebuilding values, lender acceptance, and who to contact after a loss. An affordable fire quote alone does not establish that the rest of your household's protection is in place."] },
    ] },
    es: { limits: "Compare el costo anual combinado de ambas pólizas, pero revise por separado los límites, exclusiones, deducibles, fechas e instrucciones para reportar reclamos de cada una.", sections: [
      { heading: "El seguro contra incendio es solo una parte", paragraphs: ["La póliza de vivienda del FAIR Plan cubre riesgos nombrados: únicamente las causas de pérdida enumeradas en el contrato. Las causas básicas incluyen incendio y rayo, explosión interna y humo; opciones como vandalismo cuestan más. No es una póliza que cubra automáticamente cualquier daño a una casa.", "Diferencia en condiciones (Difference in Conditions o DIC) es una póliza complementaria de otra aseguradora, no del FAIR Plan. En este contexto atiende protecciones ajenas al incendio, como robo, ciertos daños por agua y responsabilidad civil personal. Responsabilidad civil significa protección frente a reclamos cubiertos por lesiones o daños a terceros de los que usted sea legalmente responsable. El contrato DIC determina qué incluye realmente."] },
      { heading: "Imagine un incendio y luego una tubería rota", paragraphs: ["Ejemplo hipotético: un incendio daña el techo. Para esa pérdida se revisa la póliza del FAIR Plan. En otro incidente, una tubería se rompe de repente y daña los gabinetes: corresponde revisar la cobertura de agua de la póliza complementaria. Las filtraciones prolongadas, el desgaste o la falta de mantenimiento pueden quedar fuera. Tener dos pólizas no significa cobrar dos veces por el mismo daño ni eliminar todos los vacíos.", "Pregunte cuál paga la vivienda temporal después de cada tipo de pérdida. Los gastos adicionales de vivienda (additional living expense) cubren aumentos elegibles en sus gastos; el valor justo de alquiler (fair rental value) es un beneficio distinto y no debe suponerse que reembolsa hoteles. Revise también actualizaciones por código de construcción, pertenencias y riesgos excluidos de inundación o terremoto. La combinación FAIR Plan/DIC no es necesariamente idéntica a una póliza estándar de casa."] },
      { heading: "Revise los dos documentos juntos", paragraphs: ["Pídanos comparar las páginas de declaraciones, que resumen asegurados, propiedad, fechas, límites y deducibles, además de los formularios y endosos que modifican la cobertura. Confirme fechas de vigencia coordinadas, valores de reconstrucción, aceptación del prestamista y a quién llamar después de una pérdida. Una cotización económica contra incendio no demuestra que el resto de la protección del hogar esté listo."] },
    ] },
  },
  "replacement-cost-market-value": {
    sources: [residential],
    en: { limits: "Use a property-specific rebuilding estimate. Then examine extended replacement cost, code-upgrade coverage, and how the policy settles a partial or total loss.", sections: [
      { heading: "A sale price and a rebuilding estimate answer different questions", paragraphs: ["Hypothetical example: a Yorba Linda home sells for $1.1 million, but a detailed estimate puts reconstruction at $650,000. The difference does not automatically mean the insurance is too low: the sale includes land and location. Conversely, an inexpensive property can be costly to rebuild. Neither number should be copied into the policy without checking the structure's details.", "Replacement cost means the cost to repair or replace with comparable new materials, subject to the contract. Actual cash value reflects depreciation for age and condition. A replacement-cost policy can initially pay a depreciated amount and release additional eligible funds after repairs; ask about the proof and deadlines."] },
      { heading: "Look beyond the main dwelling limit", paragraphs: ["Extended replacement cost is an endorsement—an amendment to the policy—that adds a specified cushion above the dwelling limit when its conditions are met. It is not an unlimited promise. Ordinance or law coverage addresses eligible extra costs of complying with current building codes after a covered loss. Ask us to review those provisions alongside demolition, debris removal, and your updated kitchen, roof, or addition."] },
    ] },
    es: { limits: "Use un cálculo de reconstrucción específico para la propiedad. Después revise reemplazo extendido, mejoras por código y cómo se liquida una pérdida parcial o total.", sections: [
      { heading: "El precio de venta y la reconstrucción responden preguntas distintas", paragraphs: ["Ejemplo hipotético: una casa en Yorba Linda se vende por $1.1 millones, pero un cálculo detallado estima $650,000 para reconstruirla. Esa diferencia no demuestra por sí sola que el seguro sea insuficiente: el precio incluye terreno y ubicación. A la inversa, una propiedad económica puede ser costosa de reconstruir. Ninguna cifra debe copiarse a la póliza sin revisar los detalles del edificio.", "Costo de reemplazo significa reparar o sustituir con materiales nuevos comparables, sujeto al contrato. Valor real en efectivo (actual cash value) refleja depreciación por antigüedad y condición. Una póliza a costo de reemplazo puede pagar primero un monto depreciado y liberar fondos adicionales elegibles después de reparar; pregunte qué comprobantes y plazos exige."] },
      { heading: "Revise más que el límite principal", paragraphs: ["El costo de reemplazo extendido es un endoso, una modificación de la póliza, que agrega un margen específico sobre el límite de vivienda cuando se cumplen sus condiciones. No es una promesa ilimitada. La cobertura de ordenanza o ley atiende costos adicionales elegibles para cumplir códigos de construcción vigentes después de una pérdida cubierta. Pídanos revisar esas condiciones junto con demolición, retiro de escombros y cualquier cocina, techo o ampliación actualizados."] },
    ] },
  },
  "insurance-before-escrow": {
    sources: [residential],
    en: { limits: "Work backward from the closing date. Allow time for the insurer's property review, required repairs or documents, and lender acceptance—not just the initial quote.", sections: [
      { heading: "A quote is a proposal; binding starts coverage", paragraphs: ["Underwriting is the insurer's review of the applicant and property to decide whether to offer coverage and on what terms. A price displayed on a quote does not complete that review. Binding means coverage has been put into effect by someone authorized to do so, for an agreed effective date and terms.", "Hypothetical example: a buyer has a quote for a Moreno Valley home, but the insurer still needs roof photographs. If those photographs reveal a condition it will not accept, the quote alone will not protect the closing. Ask what remains outstanding while there is still time to resolve it or compare another option."] },
      { heading: "Give escrow a complete handoff", paragraphs: ["Ask the lender which coverage, deductible, and mortgagee wording it requires; the mortgagee is the lender listed as having a financial interest in the home. If two policies are needed, send both for review. Before closing, confirm the insured names, address, effective date, invoice, evidence of coverage, and payment arrangement. Ask us to identify outstanding insurance items—not to promise that a quote guarantees closing."] },
    ] },
    es: { limits: "Planifique desde la fecha de cierre hacia atrás. Reserve tiempo para la evaluación de la aseguradora, reparaciones o documentos exigidos y aceptación del prestamista, no solo para cotizar.", sections: [
      { heading: "Cotizar propone un precio; emitir la cobertura la pone en vigor", paragraphs: ["La suscripción (underwriting) es la evaluación del solicitante y la propiedad para decidir si se ofrece seguro y bajo qué condiciones. El precio de una cotización no completa esa evaluación. Poner la cobertura en vigor (binding) requiere la actuación de una persona autorizada, con fecha y condiciones acordadas.", "Ejemplo hipotético: un comprador tiene una cotización para una casa en Moreno Valley, pero faltan fotografías del techo. Si muestran una condición que la aseguradora no acepta, la cotización no protegerá por sí sola el cierre. Pregunte qué falta mientras aún hay tiempo para resolverlo o comparar otra opción."] },
      { heading: "Entregue a escrow la información completa", paragraphs: ["Pregunte al prestamista qué cobertura, deducible y datos del acreedor hipotecario exige. El acreedor hipotecario (mortgagee) es el prestamista registrado con interés financiero en la casa. Si se necesitan dos pólizas, presente ambas. Antes del cierre confirme nombres, dirección, fecha de vigencia, factura, constancia de cobertura y forma de pago. Pídanos identificar pendientes del seguro, no prometer que una cotización garantiza el cierre."] },
    ] },
  },
  "auto-garaging-address": {
    sources: [auto],
    en: { limits: "Give the insurer your actual overnight location, annual mileage, drivers, and vehicle use. A mailing address is not necessarily the garaging address.", sections: [
      { heading: "What if your mail goes somewhere else?", paragraphs: ["Hypothetical example: you receive mail at a relative's home in Moreno Valley but keep your car at your apartment in Orange County most nights. Explain both addresses. Using the mailing address simply because it gives a cheaper quote does not accurately describe the car's location.", "For split households, a student away at school, or a vehicle kept at a jobsite, tell the agent how many nights the vehicle spends at each place. Let the insurer apply its rules rather than guessing which address to list."] },
      { heading: "Report the changes that affect how you drive", paragraphs: ["A move often comes with a different commute, new household drivers, or delivery work. Those are separate questions, not just an address correction. Ask us to update the policy with the effective date of the change and explain any premium adjustment. Do not assume a move always raises or lowers the price, or that ordinary commuting and paid delivery are treated alike."] },
    ] },
    es: { limits: "Informe el lugar real donde pasa la noche el vehículo, millaje anual, conductores y uso. La dirección postal no siempre es el domicilio de garaje.", sections: [
      { heading: "¿Y si recibe correspondencia en otro lugar?", paragraphs: ["Ejemplo hipotético: recibe correo en casa de un familiar en Moreno Valley, pero su auto pasa la mayoría de las noches en su apartamento en Orange County. Explique ambas direcciones. Usar la postal solo porque genera una cotización más barata no describe correctamente la ubicación del auto.", "Si vive entre dos hogares, tiene un estudiante fuera de casa o guarda un vehículo en un lugar de trabajo, indique cuántas noches pasa en cada sitio. Deje que la aseguradora aplique sus reglas en vez de adivinar qué dirección corresponde."] },
      { heading: "Reporte los cambios en el uso del vehículo", paragraphs: ["Una mudanza puede traer otro recorrido al trabajo, nuevos conductores del hogar o trabajo de entregas. Son preguntas distintas, no solo un cambio de dirección. Pídanos actualizar la póliza desde la fecha correspondiente y explicar cualquier ajuste de prima. No suponga que mudarse siempre aumenta o reduce el precio, ni que ir al trabajo y hacer entregas pagadas se tratan igual."] },
    ] },
  },
  "general-liability-workers-compensation": {
    sources: [commercial, workers],
    en: { limits: "General liability limits and workers' compensation benefits are not interchangeable. Review both policies and the separate employer's liability limits.", sections: [
      { heading: "The same fall, two different insurance questions", paragraphs: ["Hypothetical example: a customer slips in your shop and alleges your business caused the injury. General liability is the coverage to examine for that third-party claim; a third party is someone other than the insured business in this context. If an employee falls while stocking a shelf, workers' compensation is the coverage to examine for the work injury.", "Workers' compensation provides statutory benefits—benefits established by law—for covered work-related injury or illness. Employer's liability is a separate part of the usual policy for certain employer-liability claims, with its own limits and exclusions. It is not simply another name for medical benefits."] },
      { heading: "Hiring one employee changes the conversation", paragraphs: ["California employers with one or more employees must satisfy workers' compensation requirements through insurance or authorized self-insurance. Calling someone an independent contractor does not settle their legal status. Before work starts, ask us to review duties, payroll, owner participation, and subcontractor arrangements. Keep payroll and job records current so the year-end premium audit can compare actual work with the original estimates."] },
    ] },
    es: { limits: "Los límites de responsabilidad general y los beneficios de compensación laboral no son intercambiables. Revise ambas pólizas y los límites separados de responsabilidad del empleador.", sections: [
      { heading: "La misma caída plantea dos preguntas distintas", paragraphs: ["Ejemplo hipotético: un cliente resbala en su tienda y alega que el negocio causó la lesión. Se revisa responsabilidad general para ese reclamo de un tercero; en este contexto, alguien distinto del negocio asegurado. Si un empleado cae mientras acomoda mercancía, se revisa compensación laboral por la lesión de trabajo.", "La compensación laboral brinda beneficios establecidos por ley para lesiones o enfermedades de trabajo cubiertas. La responsabilidad del empleador (employer's liability) es una parte separada de la póliza habitual para ciertos reclamos contra el empleador, con límites y exclusiones propios. No es otro nombre para los beneficios médicos."] },
      { heading: "Contratar a un empleado cambia la conversación", paragraphs: ["Los empleadores de California con uno o más empleados deben cumplir los requisitos de compensación laboral mediante seguro o autoseguro autorizado. Llamar a alguien contratista independiente no determina su situación legal. Antes de comenzar el trabajo, pídanos revisar funciones, nómina, participación de propietarios y subcontratistas. Mantenga registros para que la auditoría final compare el trabajo real con las estimaciones iniciales."] },
    ] },
  },
  "insurance-mortgage-escrow": {
    sources: [{ label: "CFPB: escrow accounts", url: "https://www.consumerfinance.gov/rules-policy/regulations/1024/17/" }],
    en: { limits: "Annual premium divided by 12 estimates only the ongoing insurance portion. It is not your complete mortgage payment or the amount due at closing.", sections: [
      { heading: "Why the monthly payment can rise by more than the premium change", paragraphs: ["An escrow account is money your mortgage servicer collects to pay scheduled expenses such as property taxes and insurance. Illustrative example: insurance rises from $1,800 to $2,400 a year. The ongoing insurance portion increases from $150 to $200 a month—a $50 difference.", "If the servicer also collects an illustrative $600 shortage over 12 months, that adds another $50 during that period. The combined increase would be $100, before any tax changes or other adjustments. A shortage means the account is below its calculated target. The actual escrow analysis and loan rules determine the amount and repayment options."] },
      { heading: "Changing insurers? Coordinate the money as well as the dates", paragraphs: ["Ask the servicer whether it has already paid the renewal, where to send the replacement invoice, and how any refund should be handled. A refund paid to you does not automatically replenish escrow. Ask us for the updated insurance documents and ask the servicer to explain its escrow calculation; those are different responsibilities. Keep the replacement coverage in force before ending the old policy."] },
    ] },
    es: { limits: "Dividir la prima anual entre 12 estima solo la parte recurrente del seguro. No representa la mensualidad hipotecaria completa ni el monto requerido al cierre.", sections: [
      { heading: "Por qué la mensualidad puede subir más que la prima", paragraphs: ["Una cuenta de escrow contiene dinero que el administrador hipotecario recauda para pagar gastos programados como impuestos y seguro. Ejemplo ilustrativo: el seguro sube de $1,800 a $2,400 al año. Su parte mensual pasa de $150 a $200, una diferencia de $50.", "Si además se recauda un faltante ilustrativo de $600 durante 12 meses, se agregan otros $50 durante ese periodo. El aumento combinado sería $100, antes de cambios de impuestos u otros ajustes. Un faltante significa que la cuenta está por debajo de su saldo objetivo calculado. El análisis real de escrow y las reglas del préstamo determinan montos y opciones de pago."] },
      { heading: "Al cambiar de aseguradora, coordine dinero y fechas", paragraphs: ["Pregunte al administrador si ya pagó la renovación, dónde enviar la nueva factura y cómo manejar un reembolso. Un reembolso que usted recibe no repone automáticamente escrow. Pídanos los documentos actualizados del seguro y solicite al administrador explicar su cálculo: son responsabilidades distintas. Mantenga la nueva cobertura vigente antes de terminar la anterior."] },
    ] },
  },
  "umbrella-insurance": {
    sources: [residential, commercial],
    en: { limits: "Compare the umbrella limit and premium alongside the home and auto limits it requires you to maintain. Do not reduce those underlying limits without checking the umbrella contract.", sections: [
      { heading: "An extra layer, not a replacement policy", paragraphs: ["Underlying insurance is the policy that responds first, such as auto liability. Illustrative example: you are responsible for a covered $700,000 injury claim, and the applicable auto liability limit is $250,000. If both policies cover the claim and all umbrella requirements are met, the umbrella could address the remaining $450,000 within its limit. This simplified example excludes defense-cost and other settlement provisions.", "An umbrella does not increase the amount available to rebuild your own home or repair your own car. Business activities, excluded drivers, certain rentals, and uninsured-motorist claims need separate attention; do not assume the umbrella covers them because you own a policy."] },
      { heading: "Check the handoff between policies", paragraphs: ["If your umbrella requires $250,000 of underlying protection but you keep only $100,000, it need not fill that $150,000 gap for you. Ask us to compare the required-limit schedule with every home, vehicle, rental, and driver. Then discuss the size of a severe liability claim and the income and assets you are trying to protect, rather than buying a round number without context."] },
    ] },
    es: { limits: "Compare el límite y la prima del seguro paraguas junto con los límites de casa y auto que exige mantener. No reduzca esos límites base sin revisar el contrato paraguas.", sections: [
      { heading: "Una capa adicional, no una póliza de reemplazo", paragraphs: ["El seguro subyacente es la póliza que responde primero, como responsabilidad de auto. Ejemplo ilustrativo: usted es responsable de un reclamo cubierto de $700,000 por lesiones y el límite aplicable del auto es $250,000. Si ambas pólizas cubren el reclamo y se cumplen los requisitos del paraguas, este podría atender los $450,000 restantes dentro de su límite. El ejemplo simplificado no incluye costos de defensa ni otros ajustes.", "El paraguas no aumenta el dinero para reconstruir su propia casa o reparar su propio auto. Actividades comerciales, conductores excluidos, ciertos alquileres y reclamos por conductores sin seguro requieren atención separada; tener un paraguas no significa que los incluya."] },
      { heading: "Revise cómo se conectan las pólizas", paragraphs: ["Si el paraguas exige $250,000 de protección base y usted mantiene solo $100,000, no tiene por qué cubrirle esa diferencia de $150,000. Pídanos comparar los límites exigidos con cada vivienda, vehículo, alquiler y conductor. Después hablemos de la magnitud de un reclamo grave y de los ingresos y activos que busca proteger, en vez de elegir una cifra redonda sin contexto."] },
    ] },
  },
  "california-auto-liability-limits": {
    sources: [auto, { label: "California DMV: insurance requirements", url: "https://www.dmv.ca.gov/portal/vehicle-registration/insurance-requirements/" }],
    en: { limits: "California's standard auto liability minimum is 30/60/15. The separate California Low Cost Automobile Insurance Program has its own eligibility and limits. A legal minimum is not a household-specific recommendation.", sections: [
      { heading: "Read the three numbers in dollars", paragraphs: ["30/60/15 means up to $30,000 for bodily injury to one person, $60,000 total for bodily injuries in one accident, and $15,000 for property damage in that accident. The property amount is not extra money for injuries, and the per-person injury limit still applies even when the total accident limit has room left.", "Illustrative example: you cause $25,000 of covered damage to another car. A $15,000 property-damage limit leaves a $10,000 gap, assuming you are responsible for the full amount and there are no other adjustments. Your liability coverage does not pay to repair your own car; that is a separate collision-coverage question."] },
      { heading: "Ask for comparable options, not just the lowest price", paragraphs: ["A quote at 100/300/100 means $100,000 per injured person, $300,000 per accident for injuries, and $100,000 for property damage. It is a comparison example, not the right answer for everyone. Ask us to show the price difference between available limits with the same drivers and other coverages, and check any umbrella requirement. Liability limits address how much the insurer can pay, not whether an accident is covered in the first place."] },
    ] },
    es: { limits: "El mínimo de responsabilidad para una póliza estándar de auto en California es 30/60/15. El programa separado California Low Cost Automobile Insurance tiene requisitos y límites propios. El mínimo legal no es una recomendación personalizada.", sections: [
      { heading: "Lea las tres cifras en dólares", paragraphs: ["30/60/15 significa hasta $30,000 por lesiones corporales a una persona, $60,000 en total por lesiones en un accidente y $15,000 por daños materiales en ese accidente. El monto para bienes no agrega dinero para lesiones. El límite por persona sigue aplicando aunque quede dinero dentro del total por accidente.", "Ejemplo ilustrativo: causa $25,000 de daños cubiertos a otro auto. Un límite de daños materiales de $15,000 deja una diferencia de $10,000, suponiendo responsabilidad por todo el monto y sin otros ajustes. Su responsabilidad civil no repara su propio auto; eso requiere revisar la cobertura de colisión por separado."] },
      { heading: "Pida opciones comparables, no solo el menor precio", paragraphs: ["Una cotización 100/300/100 significa $100,000 por persona lesionada, $300,000 por accidente para lesiones y $100,000 para daños materiales. Es un ejemplo de comparación, no la respuesta para todos. Pídanos mostrar la diferencia de precio entre límites disponibles manteniendo los mismos conductores y demás coberturas, y revisar cualquier requisito de paraguas. Los límites indican cuánto puede pagar la aseguradora, no si el accidente está cubierto."] },
    ] },
  },
  "uninsured-underinsured-motorist-california": {
    sources: [auto, { label: "California Insurance Code: uninsured and underinsured motorists", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=INS&sectionNum=11580.2." }],
    en: { limits: "Read uninsured motorist (UM) and underinsured motorist (UIM) bodily-injury limits separately from vehicle-damage coverage. Ask how payments from the responsible driver reduce the available UIM amount.", sections: [
      { heading: "Whose injuries are we talking about?", paragraphs: ["Your liability insurance addresses covered injuries you cause to others. UM/UIM bodily-injury coverage addresses covered injuries to insured people when another driver is responsible but lacks sufficient insurance. Medical bills and lost earnings are different losses; having health insurance does not make those two coverages identical.", "California UIM is not simply an extra limit stacked on top of the other driver's payment. Illustrative example: with $100,000 of applicable UIM coverage and $30,000 paid by the responsible driver's insurer, the potential remaining UIM limit is $70,000, not another $100,000. Actual recovery depends on covered damages and policy/legal requirements, including exhaustion and offsets."] },
      { heading: "Do not confuse injury protection with car repairs", paragraphs: ["Uninsured-motorist property damage has different conditions from collision; identification of the uninsured driver matters. A hit-and-run vehicle-damage claim is not automatically covered just because UM appears on your declarations. Ask us to explain bodily injury, vehicle damage, collision, and any collision-deductible waiver separately, including how to report an accident promptly and preserve the information your insurer needs."] },
    ] },
    es: { limits: "Revise los límites por lesiones de conductores sin seguro (UM) y con seguro insuficiente (UIM) por separado de los daños al vehículo. Pregunte cómo los pagos del responsable reducen el monto UIM disponible.", sections: [
      { heading: "¿De quién son las lesiones?", paragraphs: ["Su responsabilidad civil atiende lesiones cubiertas que usted causa a otros. UM/UIM para lesiones protege a personas aseguradas cuando otro conductor es responsable y no tiene seguro suficiente. Facturas médicas y salarios perdidos son pérdidas distintas; tener seguro médico no hace idénticas estas coberturas.", "En California, UIM no es simplemente otro límite que se suma completo al pago del responsable. Ejemplo ilustrativo: con $100,000 de UIM aplicable y $30,000 pagados por la aseguradora del responsable, el límite potencial restante es $70,000, no otros $100,000. El pago real depende de daños cubiertos y requisitos legales y de la póliza, incluidos agotamiento de límites y deducciones aplicables."] },
      { heading: "No confunda lesiones con reparación del auto", paragraphs: ["Los daños materiales por conductor sin seguro tienen condiciones distintas de colisión; importa identificar al conductor sin seguro. Un choque con fuga no queda automáticamente cubierto para reparar su auto solo porque UM aparezca en sus declaraciones. Pídanos explicar lesiones, daños al vehículo, colisión y cualquier exención de deducible por separado, además de cómo reportar el accidente y conservar la información necesaria."] },
    ] },
  },
  "comprehensive-collision-deductibles": {
    sources: [auto],
    en: { limits: "Compare comprehensive and collision deductibles independently. The available settlement depends on the vehicle's value and contract, not simply the amount still owed on the loan.", sections: [
      { heading: "A parking-lot collision is different from theft", paragraphs: ["Hypothetical examples: backing into a post raises a collision claim; discovering that your parked car was stolen raises a comprehensive claim. Comprehensive is also called other-than-collision coverage. Neither label means every repair is insured: routine maintenance and mechanical wear are not the purpose of these coverages.", "Illustrative example: covered repairs total $4,000. A $500 deductible leaves a simplified $3,500 payment; a $1,000 deductible leaves $3,000. This assumes sufficient limits and no other settlement adjustment. Compare the extra $500 exposure with the actual premium savings, not a promise that a higher deductible always saves a particular amount."] },
      { heading: "What if the car is a total loss?", paragraphs: ["Actual cash value is the vehicle's value considering age, condition, and other valuation factors—not the original purchase price. A loan can exceed the insurance settlement. Loan/lease gap protection, when purchased and applicable, addresses certain shortfalls under its own conditions. Ask us to compare vehicle value, deductibles, rental reimbursement, and lender requirements before removing coverage from an older car."] },
    ] },
    es: { limits: "Compare por separado los deducibles de integral y colisión. La liquidación depende del valor del vehículo y del contrato, no simplemente del saldo del préstamo.", sections: [
      { heading: "Un choque en el estacionamiento no es lo mismo que un robo", paragraphs: ["Ejemplos hipotéticos: retroceder contra un poste plantea un reclamo de colisión; descubrir que robaron el auto estacionado plantea uno de cobertura integral, también llamada comprehensive u other-than-collision. Ninguna etiqueta significa que toda reparación esté asegurada: el mantenimiento y el desgaste mecánico no son el propósito de estas coberturas.", "Ejemplo ilustrativo: las reparaciones cubiertas cuestan $4,000. Con un deducible de $500, el pago simplificado es $3,500; con uno de $1,000, es $3,000. Se supone cobertura suficiente y ningún otro ajuste. Compare los $500 adicionales de exposición con el ahorro real, sin asumir que aumentar el deducible siempre ahorra cierta cantidad."] },
      { heading: "¿Y si el auto es pérdida total?", paragraphs: ["El valor real en efectivo considera antigüedad, condición y otros factores; no es el precio original de compra. El préstamo puede superar la liquidación. La protección de diferencia de préstamo o arrendamiento (gap), cuando se compra y aplica, atiende ciertos faltantes bajo condiciones propias. Pídanos comparar valor, deducibles, reembolso de renta y requisitos del prestamista antes de quitar cobertura a un auto antiguo."] },
    ] },
  },
  "california-homeowners-coverage-limits": {
    sources: [residential, { label: "NFIP: what counts as a flood", url: "https://www.floodsmart.gov/know-your-risk/what-is-a-flood" }],
    en: { limits: "Set dwelling coverage from a current rebuilding estimate and belongings coverage from an inventory. Review each limit separately; a large dwelling limit does not make every other coverage unlimited.", sections: [
      { heading: "Give each part of the policy a job", paragraphs: ["Dwelling coverage addresses the house; other structures addresses qualifying detached structures. Personal property addresses belongings such as furniture and clothes. Loss of use addresses eligible costs when a covered loss disrupts living at home. Personal liability addresses covered claims that you are responsible for injury or damage to others. These are separate protections with separate rules.", "Hypothetical example: a covered fire damages the kitchen, destroys furniture, and requires temporary housing. Those costs raise dwelling, personal-property, and loss-of-use questions—not one interchangeable pot of money. Ask about both dollar and time limits for temporary living expenses."] },
      { heading: "Water damage needs a more specific question", paragraphs: ["A suddenly burst pipe, water backing up through a sewer, and water flowing across land into the house are different events. A standard home policy's water-damage provision does not automatically cover all three. Water backup often needs an endorsement, meaning a policy amendment, while flood generally needs separate coverage. Earthquake shaking also needs separate review.", "Bring your declarations and endorsements. Ask us to compare replacement cost versus depreciation, code-upgrade costs, jewelry sublimits, and the deductible for each scenario. If a quote is cheaper because a protection was removed, that is a coverage tradeoff—not the same insurance at a better price."] },
    ] },
    es: { limits: "Determine vivienda con un cálculo actual de reconstrucción y pertenencias con un inventario. Revise cada límite por separado; un límite alto de vivienda no vuelve ilimitadas las demás coberturas.", sections: [
      { heading: "Cada parte de la póliza tiene una función", paragraphs: ["Vivienda atiende la casa; otras estructuras atiende construcciones separadas que califican. Bienes personales atiende pertenencias como muebles y ropa. Pérdida de uso atiende costos elegibles cuando una pérdida cubierta impide vivir normalmente en casa. Responsabilidad civil atiende reclamos cubiertos por lesiones o daños a terceros de los que usted sea responsable. Son protecciones separadas con reglas distintas.", "Ejemplo hipotético: un incendio cubierto daña la cocina, destruye muebles y obliga a buscar alojamiento temporal. Esos costos corresponden a preguntas de vivienda, bienes personales y pérdida de uso, no a un fondo intercambiable. Pregunte por límites de dinero y tiempo para los gastos adicionales de vivienda."] },
      { heading: "Los daños por agua requieren una pregunta más específica", paragraphs: ["Una tubería que se rompe repentinamente, agua que regresa por el drenaje y agua que entra desde el terreno son eventos distintos. La cobertura de agua de una póliza de casa no incluye automáticamente los tres. El retroceso de agua suele requerir un endoso, una modificación de la póliza, mientras que inundación generalmente necesita cobertura separada. El movimiento sísmico también requiere otra revisión.", "Traiga declaraciones y endosos. Pídanos comparar costo de reemplazo frente a depreciación, mejoras por código, límites especiales de joyería y deducibles para cada situación. Si una cotización baja porque eliminaron una protección, es un cambio de cobertura, no el mismo seguro a mejor precio."] },
    ] },
  },
  "renters-insurance-california": {
    sources: [residential],
    en: { limits: "Build your belongings limit from a room-by-room replacement inventory. Check the lease's liability requirement separately; meeting it does not establish that your belongings limit is enough.", sections: [
      { heading: "Start with everything you would have to buy again", paragraphs: ["It is easy to remember a laptop and forget bedding, cookware, shoes, and the contents of every drawer. Add them at today's replacement prices. Replacement-cost coverage and actual cash value are not the same: actual cash value accounts for depreciation, while replacement-cost coverage has conditions for recovering the cost of comparable new items.", "Hypothetical example: a covered apartment fire damages your furniture and forces you out during repairs. Personal property is the coverage to review for the furniture. Additional living expense addresses eligible increased living costs, not every dollar you spend while away. Keep receipts and compare your temporary costs with your normal expenses."] },
      { heading: "Your roommate and your guests raise different questions", paragraphs: ["A roommate is not automatically an insured person on your policy. A guest alleging that you caused an injury raises a liability question instead. Tell us who lives with you, whether you have pets, and whether you run a business at home. Ask us to check insured residents, theft limits for valuable items, and temporary-housing protection—not just produce a certificate for the landlord."] },
    ] },
    es: { limits: "Calcule pertenencias con un inventario por habitación a precios de reemplazo. Revise aparte la responsabilidad exigida en el contrato; cumplirla no demuestra que el límite de pertenencias alcance.", sections: [
      { heading: "Empiece por todo lo que tendría que comprar otra vez", paragraphs: ["Es fácil recordar la computadora y olvidar sábanas, utensilios, zapatos y el contenido de los cajones. Súmelos a precios actuales. Costo de reemplazo y valor real en efectivo no son iguales: el segundo descuenta depreciación; el primero tiene condiciones para recuperar el costo de artículos nuevos comparables.", "Ejemplo hipotético: un incendio cubierto daña sus muebles y obliga a salir del apartamento durante reparaciones. Para los muebles se revisa bienes personales. Los gastos adicionales de vivienda atienden aumentos elegibles en el costo de vivir, no cada dólar gastado fuera. Conserve recibos y compare los gastos temporales con los normales."] },
      { heading: "Su compañero de vivienda y sus invitados plantean preguntas distintas", paragraphs: ["Un compañero no queda asegurado automáticamente en su póliza. Un invitado que alega que usted causó una lesión plantea una pregunta de responsabilidad civil. Díganos quién vive con usted, si tiene mascotas y si trabaja por cuenta propia desde casa. Pídanos revisar residentes asegurados, límites de robo para objetos valiosos y alojamiento temporal, no solo emitir una constancia para el propietario."] },
    ] },
  },
  "condo-insurance-california": {
    sources: [residential],
    en: { limits: "Use the association's insurance responsibilities and the unit's interior rebuilding cost to choose building coverage. A loss-assessment limit does not cover every assessment the association can charge.", sections: [
      { heading: "What do HO-6, HOA, and CC&Rs mean?", paragraphs: ["HO-6 is a common name for a condo unit-owner policy. HOA means homeowners association. Its master insurance policy covers the association's insured property and liability. CC&Rs are the recorded covenants, conditions, and restrictions that help establish owners' responsibilities. Read those documents together rather than assuming that 'walls-in' describes every association correctly.", "Hypothetical example: a covered kitchen fire damages custom cabinets. Whether the master policy or your unit policy addresses those cabinets depends on the insurance boundary and improvements coverage. A certificate showing that the building is insured does not resolve that question."] },
      { heading: "An assessment is not automatically an insured loss", paragraphs: ["Loss assessment is coverage for certain qualifying charges allocated to unit owners after a covered property or liability loss. A special assessment for routine roof replacement or inadequate reserves is not the same thing. Assessments of a master-policy deductible can have separate restrictions. Send us the master declarations, deductible details, relevant CC&Rs, and your improvements list so we can compare the actual gap."] },
    ] },
    es: { limits: "Use las responsabilidades de la asociación y el costo de reconstruir el interior para elegir cobertura del edificio. Un límite de cuotas por pérdidas no cubre cualquier cargo de la asociación.", sections: [
      { heading: "¿Qué significan HO-6, HOA y CC&R?", paragraphs: ["HO-6 es un nombre habitual para la póliza del dueño de una unidad. HOA significa asociación de propietarios. Su póliza maestra cubre los bienes y la responsabilidad asegurados de la asociación. Los CC&R son convenios, condiciones y restricciones registrados que ayudan a establecer responsabilidades. Lea esos documentos juntos; la expresión 'de las paredes hacia adentro' no describe correctamente todas las asociaciones.", "Ejemplo hipotético: un incendio cubierto en la cocina daña gabinetes personalizados. Que los atienda la póliza maestra o la de su unidad depende de la división de responsabilidades y la cobertura de mejoras. Una constancia de que el edificio tiene seguro no resuelve esa pregunta."] },
      { heading: "Una cuota no es automáticamente una pérdida asegurada", paragraphs: ["La cobertura de cuotas por pérdidas (loss assessment) atiende ciertos cargos elegibles distribuidos entre propietarios después de una pérdida cubierta de propiedad o responsabilidad. Una cuota para reemplazar un techo por mantenimiento o reponer reservas insuficientes es distinta. Los cargos por el deducible de la póliza maestra pueden tener restricciones separadas. Envíenos declaraciones maestras, deducibles, CC&R pertinentes y mejoras para comparar el vacío real."] },
    ] },
  },
  "landlord-insurance-california": {
    sources: [residential],
    en: { limits: "Compare rebuilding cost, landlord-owned contents, premises liability, and loss of rents separately. Ordinary unpaid rent and vacancy are not the same as rent lost because of covered property damage.", sections: [
      { heading: "Lost rent needs a covered reason", paragraphs: ["Hypothetical example: a covered fire makes your rental house uninhabitable during repairs. Loss-of-rents or fair-rental-value coverage is the provision to examine for eligible lost rental income, subject to its time and dollar limits. A tenant simply stopping payment does not trigger that same property-loss benefit.", "Your appliances or furniture supplied with the rental are different from the tenant's belongings. List what you own and confirm the contents coverage. Premises liability addresses certain claims that you are legally responsible for injury or damage connected with the property; it is not a promise to resolve every landlord-tenant dispute."] },
      { heading: "Tell the insurer when the rental changes", paragraphs: ["A yearly lease, short stays, a vacant renovation, and a home you occupy yourself present different risks. Before changing use, ask us to check eligibility, vacancy provisions, and any rental restrictions. Bring the lease, monthly rent, ownership or trust details, and renovation timeline. Those facts help match the policy to the property you actually operate."] },
    ] },
    es: { limits: "Compare por separado reconstrucción, bienes del arrendador, responsabilidad y pérdida de rentas. La renta impaga y la vacancia no equivalen a perder renta por daños materiales cubiertos.", sections: [
      { heading: "La pérdida de renta necesita una causa cubierta", paragraphs: ["Ejemplo hipotético: un incendio cubierto deja inhabitable su casa de alquiler durante las reparaciones. Pérdida de rentas o valor justo de alquiler es la condición que debe revisarse para los ingresos elegibles perdidos, con límites de tiempo y dinero. Que el inquilino deje de pagar no activa ese mismo beneficio por daños materiales.", "Sus electrodomésticos o muebles proporcionados con el alquiler son distintos de las pertenencias del inquilino. Enumere lo que usted posee y confirme cobertura de contenido. Responsabilidad del inmueble atiende ciertos reclamos por lesiones o daños relacionados con la propiedad de los que sea legalmente responsable; no promete resolver cualquier disputa entre arrendador e inquilino."] },
      { heading: "Avise cuando cambie el uso del alquiler", paragraphs: ["Un contrato anual, estancias cortas, una remodelación desocupada y una casa que usted habita presentan riesgos diferentes. Antes de cambiar el uso, pídanos revisar elegibilidad, condiciones de vacancia y restricciones de alquiler. Traiga contrato, renta mensual, datos del propietario o fideicomiso y calendario de remodelación. Eso permite ajustar la póliza al inmueble que realmente opera."] },
    ] },
  },
  "life-insurance-needs-california": {
    sources: [{ label: "California Department of Insurance: life insurance guide", url: "https://www.insurance.ca.gov/01-consumers/105-type/95-guides/07-life/life-ins-guide.cfm" }],
    en: { limits: "Estimate the obligations you want to fund, then subtract resources actually available to survivors. An income multiplier alone can miss caregiving, existing debts, or a nonworking partner's contribution.", sections: [
      { heading: "Turn a benefit amount into a family plan", paragraphs: ["A beneficiary is the person or entity designated to receive the death benefit. Illustrative planning example: $40,000 of annual household support for ten years is $400,000. Add $150,000 of other obligations and subtract $100,000 of available resources to reach a $450,000 starting estimate. This simplified calculation ignores inflation, investment returns, taxes, and changing needs; it is not a personal recommendation. Avoid counting the same mortgage cost twice.", "Unpaid caregiving has value too. If a parent who provides childcare dies, replacing that help can create a real expense even if no salary is lost. Review who depends on you, how long the need lasts, and which employer-provided coverage would remain if you changed jobs."] },
      { heading: "Match the duration and the funding commitment", paragraphs: ["Term coverage fits a defined period; permanent coverage involves longer-term funding and cash-value provisions. Cash value is not automatically an extra payment on top of the death benefit. Ask to see guaranteed and nonguaranteed values separately, the cost after a term's level-premium period, and conversion deadlines. Before replacing an existing policy, compare surrender charges, new underwriting, and contestability provisions, and keep the old coverage until the replacement is confirmed in force."] },
    ] },
    es: { limits: "Calcule las obligaciones que quiere financiar y reste recursos realmente disponibles para los sobrevivientes. Multiplicar ingresos puede omitir cuidados, deudas o la contribución de una pareja sin salario.", sections: [
      { heading: "Convierta el beneficio en un plan familiar", paragraphs: ["El beneficiario es la persona o entidad designada para recibir el beneficio por fallecimiento. Ejemplo ilustrativo: $40,000 anuales de apoyo durante diez años suman $400,000. Agregar $150,000 de otras obligaciones y restar $100,000 disponibles da una estimación inicial de $450,000. Este cálculo simplificado omite inflación, rendimientos, impuestos y necesidades cambiantes; no es una recomendación personal. Evite contar dos veces el mismo costo hipotecario.", "Los cuidados no remunerados también tienen valor. Si fallece quien cuida a los hijos, reemplazar esa ayuda puede generar un gasto real aunque no se pierda un salario. Revise quién depende de usted, por cuánto tiempo y qué seguro del empleador conservaría si cambiara de trabajo."] },
      { heading: "Coordine la duración y el compromiso de pago", paragraphs: ["El seguro temporal corresponde a un periodo definido; el permanente implica financiamiento a largo plazo y condiciones de valor en efectivo. Ese valor no se paga automáticamente además del beneficio por fallecimiento. Pida separar valores garantizados y no garantizados, costo después del periodo de prima nivelada y plazos de conversión. Antes de reemplazar una póliza, compare cargos de rescate, nueva evaluación y periodos de impugnación, y conserve la anterior hasta confirmar que la nueva está vigente."] },
    ] },
  },
  "earthquake-insurance-retrofit-discounts": {
    sources: [{ label: "CEA: homeowners coverages and deductibles", url: "https://www.earthquakeauthority.com/california-earthquake-insurance-policies/homeowners/coverages-and-deductibles" }, { label: "CEA: verified retrofit discounts", url: "https://www.earthquakeauthority.com/california-earthquake-insurance-policies/earthquake-insurance-policy-premium-discounts" }],
    en: { limits: "Compare the dollar deductible for each offered CEA option. Lower percentage choices are not available for every home, and personal property and loss of use have separate selections.", sections: [
      { heading: "A percentage deductible can be a large amount", paragraphs: ["Illustrative example: 15% of a $600,000 dwelling limit is $90,000. If eligible dwelling damage is $120,000, the simplified amount above that deductible is $30,000, assuming adequate limits and no other adjustments. The deductible is not 15% of the $120,000 repair bill.", "California Earthquake Authority (CEA) Standard Homeowners and Homeowners Choice policies handle coverage selections and deductibles differently. Under current CEA options, included or selected loss-of-use coverage has no deductible, so do not assume you must first fund the entire dwelling deductible to use that benefit. Its other conditions and limits still apply."] },
      { heading: "A retrofit is structural work, not a coverage promise", paragraphs: ["Foundation bolting helps connect a house to its foundation; bracing reinforces vulnerable short walls below the main floor. Whether work qualifies for a CEA discount depends on the home's construction and verified compliance with the program. Ask about documentation before paying for work. Have us compare the available coverage choices, dollar deductibles, and verified discount—not just the lowest percentage advertised online."] },
    ] },
    es: { limits: "Compare en dólares el deducible de cada opción CEA ofrecida. Los porcentajes menores no están disponibles para todas las casas; bienes personales y pérdida de uso tienen selecciones separadas.", sections: [
      { heading: "Un deducible porcentual puede representar mucho dinero", paragraphs: ["Ejemplo ilustrativo: el 15% de un límite de vivienda de $600,000 es $90,000. Si el daño elegible a la vivienda es $120,000, el monto simplificado que supera el deducible es $30,000, suponiendo límites suficientes y sin otros ajustes. El deducible no es el 15% de la reparación de $120,000.", "Las pólizas Standard Homeowners y Homeowners Choice de California Earthquake Authority (CEA) manejan de manera distinta selecciones y deducibles. En las opciones actuales, la pérdida de uso incluida o seleccionada no tiene deducible; no suponga que debe pagar primero todo el deducible de vivienda para usar ese beneficio. Sus demás condiciones y límites siguen aplicando."] },
      { heading: "El refuerzo es trabajo estructural, no una garantía de seguro", paragraphs: ["El anclaje ayuda a conectar la casa con sus cimientos; el arriostramiento refuerza muros bajos vulnerables debajo del piso principal. Que el trabajo califique para un descuento CEA depende de construcción y cumplimiento verificado del programa. Pregunte qué documentación necesita antes de pagar. Pídanos comparar coberturas disponibles, deducibles en dólares y descuento verificado, no solo el menor porcentaje anunciado."] },
    ] },
  },
  "wildfire-readiness-home-hardening": {
    sources: [{ label: "CAL FIRE: home hardening", url: "https://readyforwildfire.org/prepare-for-wildfire/hardening-your-home/" }, { label: "CDI: Safer from Wildfires", url: "https://www.insurance.ca.gov/01-consumers/200-wrr/Safer-from-Wildfires.cfm" }],
    en: { limits: "Reduce ignition opportunities and document completed work. A mitigation discount, an offer of insurance, and the amount payable after a loss are three different questions.", sections: [
      { heading: "Think about where an ember could land", paragraphs: ["Home hardening means changing vulnerable building features, such as vents, so the structure is harder to ignite. Defensible space means managing vegetation and other fuels around it. Neither is simply a clean-looking yard. Leaves in a gutter or combustible material against a wall can create a path for fire even when the lawn is maintained.", "Hypothetical example: you replace vulnerable vents and remove combustible storage next to the house. Save dated photographs, invoices, and product information. Ask the insurer which completed actions qualify and what proof it needs. Do not assume a contractor's description alone establishes a discount or that the work guarantees renewal."] },
      { heading: "Prepare for leaving, not just for rebuilding", paragraphs: ["Keep a current home inventory, policy numbers, and claim contacts accessible away from the property. Follow local evacuation instructions; do not stay to collect insurance evidence. Before fire season, ask us to review rebuilding assumptions and temporary-living limits alongside your mitigation records. For required clearance and construction work, use current CAL FIRE and local guidance rather than treating an insurance checklist as a permit or fire-code determination."] },
    ] },
    es: { limits: "Reduzca puntos de ignición y documente el trabajo. Un descuento por mitigación, una oferta de seguro y el pago de un reclamo son tres preguntas diferentes.", sections: [
      { heading: "Piense dónde podría caer una brasa", paragraphs: ["Fortalecer la casa (home hardening) significa modificar partes vulnerables, como ventilaciones, para dificultar la ignición. El espacio defendible consiste en manejar vegetación y otros combustibles alrededor. No basta con que el jardín se vea limpio. Hojas en canaletas o materiales combustibles contra una pared pueden dar paso al fuego aunque el césped esté cuidado.", "Ejemplo hipotético: reemplaza ventilaciones vulnerables y retira materiales combustibles junto a la casa. Guarde fotos fechadas, facturas y especificaciones. Pregunte qué acciones terminadas califican y qué prueba exige la aseguradora. La descripción de un contratista no establece por sí sola un descuento, y el trabajo no garantiza renovación."] },
      { heading: "Prepárese para salir, no solo para reconstruir", paragraphs: ["Mantenga inventario, números de póliza y contactos de reclamos accesibles fuera de la propiedad. Siga instrucciones locales de evacuación; no se quede para reunir pruebas del seguro. Antes de la temporada de incendios, pídanos revisar reconstrucción y vivienda temporal junto con sus documentos de mitigación. Use orientación vigente de CAL FIRE y autoridades locales para trabajos y despejes exigidos; una lista del seguro no sustituye permisos ni una determinación del código contra incendios."] },
    ] },
  },
  "commercial-general-liability-limits": {
    sources: [commercial],
    en: { limits: "Compare the per-occurrence limit, applicable aggregate, exclusions, and contract endorsements together. A certificate listing a limit does not expand the underlying policy.", sections: [
      { heading: "What does $1 million / $2 million mean?", paragraphs: ["Commercial general liability (GL) addresses certain claims by others for injury, property damage, and defined personal or advertising injury, such as certain defamation allegations. An occurrence limit caps payment for a covered event. An aggregate caps specified covered payments during the applicable period, usually the policy term; products-completed operations commonly has a separate aggregate.", "Illustrative example: a policy has a $1 million occurrence limit and a $2 million general aggregate. After $1.5 million of payments subject to that aggregate, $500,000 remains for it. The next claim does not automatically have a fresh $1 million available. This example assumes no separate aggregate applies and ignores other settlement provisions."] },
      { heading: "Contracts need more than a certificate", paragraphs: ["An additional insured is another person or organization granted specified protection by the policy, often through an endorsement. A certificate is evidence of coverage, not the endorsement itself. Completed operations concerns liability arising from finished work or products; it does not promise to replace defective work as a warranty. Send us the actual contract and a description of the work so we can compare required wording, covered operations, and exclusions before you start."] },
    ] },
    es: { limits: "Compare límite por ocurrencia, agregado aplicable, exclusiones y endosos contractuales juntos. Una constancia que muestra un límite no amplía la póliza.", sections: [
      { heading: "¿Qué significa $1 millón / $2 millones?", paragraphs: ["La responsabilidad civil general comercial (GL) atiende ciertos reclamos de terceros por lesiones, daños materiales y lesiones personales o publicitarias definidas, como algunas acusaciones de difamación. El límite por ocurrencia restringe el pago por un evento cubierto. El agregado restringe pagos cubiertos específicos durante el periodo aplicable, generalmente la vigencia; productos y operaciones terminadas suele tener otro agregado.", "Ejemplo ilustrativo: hay $1 millón por ocurrencia y $2 millones de agregado general. Después de $1.5 millones en pagos sujetos a ese agregado, quedan $500,000. El siguiente reclamo no recibe automáticamente otro $1 millón completo. Se supone que no aplica un agregado separado y se omiten otros ajustes."] },
      { heading: "Los contratos requieren más que una constancia", paragraphs: ["Un asegurado adicional es otra persona u organización que recibe protección específica bajo la póliza, frecuentemente mediante un endoso. La constancia demuestra cobertura, pero no es el endoso. Operaciones terminadas se refiere a responsabilidad por trabajos o productos finalizados; no promete reemplazar trabajo defectuoso como una garantía. Envíenos el contrato y la descripción del trabajo para comparar requisitos, operaciones cubiertas y exclusiones antes de comenzar."] },
    ] },
  },
  "business-owners-policy-property-income": {
    sources: [commercial],
    en: { limits: "Inventory property at current values and estimate a realistic restoration period. Business income is not necessarily unlimited and does not simply reimburse all sales you miss.", sections: [
      { heading: "A closed shop loses more than its equipment", paragraphs: ["A business owners policy (BOP) packages coverages for eligible businesses. Business income concerns covered lost net income and continuing expenses, not simply gross sales. Extra expense addresses eligible additional costs of keeping the business operating or reducing a shutdown. The policy's trigger, waiting period, restoration period, and limits determine payment.", "Hypothetical example: a covered fire closes a small shop for repairs. Property coverage addresses damaged insured fixtures and stock. Business income is the provision to examine for covered lost income and continuing expenses; extra expense is the provision to examine for an eligible temporary location. A slow sales month without a covered trigger is a different situation."] },
      { heading: "How long would reopening really take?", paragraphs: ["List the time for debris removal, permits, construction, replacement equipment, and inspections. Replacing a specialized machine can take longer than repainting a room. Ask us to review a business-income worksheet, leases, inventory, and seasonal sales. Also distinguish a mechanical breakdown, a utility outage, and flood from a covered fire; those events need their own coverage review rather than assuming the package treats them alike."] },
    ] },
    es: { limits: "Inventaríe bienes a valores actuales y estime un periodo realista de restauración. Los ingresos comerciales no son necesariamente ilimitados ni reembolsan simplemente todas las ventas perdidas.", sections: [
      { heading: "Un negocio cerrado pierde más que su equipo", paragraphs: ["Una póliza para dueños de negocio (BOP) reúne coberturas para empresas elegibles. Ingresos comerciales se refiere a ingresos netos perdidos cubiertos y gastos que continúan, no simplemente ventas brutas. Gastos extra atiende costos adicionales elegibles para seguir operando o reducir el cierre. El evento que activa cobertura, espera, periodo de restauración y límites determinan el pago.", "Ejemplo hipotético: un incendio cubierto cierra una tienda durante reparaciones. Propiedad atiende instalaciones y mercancía aseguradas dañadas. Ingresos comerciales es la condición para revisar ingresos cubiertos perdidos y gastos continuos; gastos extra corresponde a un local temporal elegible. Un mes de ventas bajas sin evento cubierto es distinto."] },
      { heading: "¿Cuánto tardaría realmente en reabrir?", paragraphs: ["Considere retiro de escombros, permisos, construcción, equipo de reemplazo e inspecciones. Sustituir una máquina especializada puede tardar más que pintar. Pídanos revisar la hoja de ingresos comerciales, contratos, inventario y ventas estacionales. Distinga también avería mecánica, interrupción de servicios e inundación de un incendio cubierto; cada evento necesita revisión, sin suponer que el paquete los trata igual."] },
    ] },
  },
  "workers-compensation-california": {
    sources: [workers, commercial],
    en: { limits: "Workers' compensation benefits follow law. Employer's liability is a separate policy part with stated limits; do not confuse those dollar limits with the employee's statutory benefits.", sections: [
      { heading: "Why a payroll estimate changes the final price", paragraphs: ["A classification groups work according to its duties and risk; an office employee and an installer do not perform the same work. An audit compares the payroll and operations estimated at the start with the actual exposure during the term. It is a premium reconciliation, not a new claim.", "Illustrative example: an assumed rate of $4 per $100 of payroll produces $8,000 on $200,000 of payroll. If actual payroll is $250,000, the same simplified calculation is $10,000—a $2,000 difference. These are invented teaching figures, not market rates or a quote; actual premiums include other factors, fees, and possible minimum premiums."] },
      { heading: "Do not wait until someone gets hurt", paragraphs: ["A California business with one or more employees must satisfy workers' compensation requirements through insurance or authorized self-insurance. Owner exclusions and contractor status require specific review; a 1099 label does not decide the issue. Ask us to review job duties and payroll before hiring, then report changes during the year. Keep payroll detail, subcontractor insurance records, and the insurer's injury-reporting instructions accessible."] },
    ] },
    es: { limits: "Los beneficios de compensación laboral siguen la ley. Responsabilidad del empleador es una parte separada con límites definidos; no confunda esos montos con los beneficios legales del empleado.", sections: [
      { heading: "Por qué la nómina estimada cambia el precio final", paragraphs: ["Una clasificación agrupa trabajos según funciones y riesgo; un empleado de oficina y un instalador no hacen lo mismo. La auditoría compara nómina y operaciones estimadas con la exposición real durante la vigencia. Es una conciliación de prima, no un nuevo reclamo.", "Ejemplo ilustrativo: una tarifa supuesta de $4 por cada $100 de nómina produce $8,000 sobre $200,000. Si la nómina real es $250,000, el cálculo simplificado da $10,000, una diferencia de $2,000. Son cifras inventadas para explicar, no tarifas de mercado ni cotización; la prima real incluye otros factores, cargos y posibles mínimos."] },
      { heading: "No espere a que ocurra una lesión", paragraphs: ["Un negocio de California con uno o más empleados debe cumplir los requisitos mediante seguro o autoseguro autorizado. Exclusiones de propietarios y condición de contratista necesitan revisión específica; un formulario 1099 no decide el asunto. Pídanos revisar funciones y nómina antes de contratar y reporte cambios durante el año. Mantenga accesibles nómina detallada, comprobantes de seguro de subcontratistas e instrucciones para reportar lesiones."] },
    ] },
  },
  "commercial-auto-california": {
    sources: [commercial],
    en: { limits: "A combined single limit is one liability amount shared by covered injury and property-damage claims for an accident. Verify contractual and regulatory requirements for the actual vehicle and operation.", sections: [
      { heading: "Which vehicles does the policy actually cover?", paragraphs: ["Covered-auto symbols are codes on the policy that identify categories of vehicles for each coverage. A symbol for liability does not establish that every vehicle also has collision coverage. Hired autos are vehicles the business leases, hires, rents, or borrows as defined by the contract; non-owned autos commonly include employees' personal cars used for work.", "Hypothetical example: an employee uses a personal car to make a bank deposit for the business and causes an accident. The business's non-owned auto liability is a coverage question. Damage to the employee's own car is a separate question; liability protection for the business is not automatically physical-damage insurance for that car."] },
      { heading: "Describe the work behind the wheel", paragraphs: ["Tell us who owns each vehicle, what it carries, where it is kept, who drives it, and how far it travels. A contractor's pickup, a delivery van, and a vehicle carrying passengers for a fee are not interchangeable uses. Ask us to compare liability, comprehensive, collision, hired/non-owned coverage, and any required filings. Do not rely on 'commercial auto' as proof that all cargo, drivers, or uses qualify."] },
    ] },
    es: { limits: "Un límite único combinado comparte un monto de responsabilidad entre lesiones y daños materiales cubiertos de un accidente. Verifique requisitos contractuales y regulatorios para el vehículo y la operación reales.", sections: [
      { heading: "¿Qué vehículos cubre realmente la póliza?", paragraphs: ["Los símbolos de autos cubiertos son códigos que identifican categorías de vehículos para cada cobertura. Un símbolo de responsabilidad no demuestra que todos tengan colisión. Autos contratados (hired autos) son los arrendados, rentados o prestados al negocio según el contrato; autos no propios (non-owned autos) suelen incluir vehículos personales de empleados usados para trabajar.", "Ejemplo hipotético: un empleado usa su auto para hacer un depósito bancario del negocio y causa un accidente. Corresponde revisar responsabilidad de autos no propios del negocio. Reparar el auto del empleado es otra pregunta; proteger la responsabilidad de la empresa no asegura automáticamente daños a ese vehículo."] },
      { heading: "Describa el trabajo que se hace al conducir", paragraphs: ["Díganos quién posee cada vehículo, qué transporta, dónde se guarda, quién lo maneja y qué distancia recorre. Una camioneta de contratista, una de entregas y un vehículo con pasajeros de pago no tienen usos intercambiables. Pídanos comparar responsabilidad, integral, colisión, autos contratados/no propios y registros exigidos. La etiqueta 'auto comercial' no comprueba que toda carga, conductor o uso califique."] },
    ] },
  },
  "cyber-professional-liability-california": {
    sources: [commercial, { label: "NAIC and FTC: cyber insurance for small businesses", url: "https://content.naic.org/sites/default/files/inline-files/cyber-insurance-naic.pdf" }],
    en: { limits: "Compare each coverage's own limit, deductible or retention, reporting conditions, and exclusions. A headline cyber limit does not mean every fraud or interruption receives that full amount.", sections: [
      { heading: "A stolen file is different from a costly mistake", paragraphs: ["Cyber insurance addresses specified digital incidents and their consequences. First-party coverage concerns your business's own eligible costs, such as incident response or data restoration. Third-party coverage concerns covered claims against you. Professional liability, also called errors and omissions (E&O), concerns allegations that your professional services caused a client's loss.", "Hypothetical examples: an intruder steals customer records, requiring a response under applicable law; separately, a consultant's error causes a client financial harm. Those events raise different coverage questions. A fraudulent email directing a payment also needs a specific funds-transfer or social-engineering review; do not assume every cyber policy reimburses that money."] },
      { heading: "Dates and security answers matter", paragraphs: ["Claims-made coverage ties protection to when a claim is first made and, where required, reported. A retroactive date identifies how far back eligible acts can go. Moving that date forward or allowing coverage to lapse can leave earlier work exposed. Ask us to compare those dates before changing insurers.", "Multifactor authentication (MFA) adds a verification step beyond a password. Describe your actual security controls, backups, vendors, and services accurately. Ask who to call first after an incident and whether the insurer must approve response providers or expenses; do not wait until after hiring help to discover a condition."] },
    ] },
    es: { limits: "Compare límite, deducible o retención, condiciones de reporte y exclusiones de cada cobertura. El límite principal cibernético no significa que todo fraude o interrupción reciba ese monto completo.", sections: [
      { heading: "Un archivo robado no es lo mismo que un error costoso", paragraphs: ["El seguro cibernético atiende incidentes digitales específicos y sus consecuencias. Cobertura de primera parte se refiere a costos elegibles de su propio negocio, como respuesta o restauración de datos. Cobertura de terceros atiende reclamos cubiertos contra usted. Responsabilidad profesional, o errores y omisiones (E&O), atiende alegaciones de que sus servicios causaron pérdidas a un cliente.", "Ejemplos hipotéticos: un intruso roba registros de clientes y se requiere responder conforme a la ley; en otro caso, el error de un consultor causa una pérdida financiera. Son preguntas de cobertura distintas. Un correo fraudulento que ordena un pago requiere revisar específicamente transferencias o ingeniería social; no suponga que toda póliza cibernética reembolsa ese dinero."] },
      { heading: "Importan las fechas y sus respuestas sobre seguridad", paragraphs: ["La cobertura por reclamos presentados (claims-made) depende de cuándo se presenta por primera vez el reclamo y, cuando se exige, cuándo se reporta. La fecha retroactiva determina desde cuándo pueden considerarse actos elegibles. Adelantarla o interrumpir la póliza puede dejar trabajos anteriores expuestos. Pídanos comparar esas fechas antes de cambiar de aseguradora.", "La autenticación multifactor (MFA) agrega una verificación además de la contraseña. Describa con precisión controles reales, copias de seguridad, proveedores y servicios. Pregunte a quién llamar primero y si la aseguradora debe aprobar proveedores o gastos de respuesta; no espere a contratar ayuda para descubrir una condición."] },
    ] },
  },
  "california-home-insurance-non-renewal": {
    sources: [residential, { label: "CFPB: force-placed homeowners insurance", url: "https://www.consumerfinance.gov/ask-cfpb/what-can-i-do-if-my-mortgage-lender-servicer-is-charging-me-for-force-placed-homeowners-insurance-en-219/" }],
    en: { limits: "Use the expiration date on the notice to plan the next steps. Verify notice requirements and any disaster protection with CDI; a pending review is not confirmation that coverage continues.", sections: [
      { heading: "Separate a request for reconsideration from a replacement plan", paragraphs: ["Hypothetical example: a notice relies on an old roof photograph, but you replaced the roof last year. Send the invoice and current photographs and ask for written reconsideration. At the same time, pursue replacement coverage before expiration. Submitting evidence does not itself reverse the notice or extend the policy.", "An admitted insurer is licensed by California to transact that insurance. Excess-and-surplus coverage is placed through a different regulated market for risks that need it; protections and policy terms differ. DIC means Difference in Conditions, a companion policy that addresses specified gaps alongside FAIR Plan fire coverage. Ask for these distinctions in the comparison rather than assuming the proposals are equivalent."] },
      { heading: "Protect the lender handoff without settling for a gap", paragraphs: ["Force-placed insurance is coverage arranged by a mortgage servicer when required property insurance is missing or not documented. It protects the lender's interest and is not a substitute for a full review of your belongings or liability protection. Ask us to compare replacement terms and send evidence to the servicer. Confirm actual coverage in force, its effective date, and lender receipt before considering the issue resolved."] },
    ] },
    es: { limits: "Use el vencimiento del aviso para planear. Verifique requisitos y protecciones por desastre con CDI; una revisión pendiente no confirma que la cobertura continúe.", sections: [
      { heading: "Separe la reconsideración del plan de reemplazo", paragraphs: ["Ejemplo hipotético: el aviso usa una foto antigua del techo, pero usted lo reemplazó el año pasado. Envíe factura y fotos actuales y pida reconsideración por escrito. Al mismo tiempo, busque reemplazo antes del vencimiento. Presentar pruebas no revoca por sí solo el aviso ni extiende la póliza.", "Una aseguradora admitida tiene licencia de California para ofrecer ese seguro. Las líneas excedentes (excess-and-surplus) usan otro mercado regulado para riesgos que lo necesitan; condiciones y protecciones difieren. DIC significa diferencia en condiciones, una póliza complementaria que atiende vacíos específicos junto al seguro contra incendio FAIR Plan. Pida explicar esas diferencias sin suponer propuestas equivalentes."] },
      { heading: "Coordine con el prestamista sin dejar un vacío", paragraphs: ["El seguro impuesto por el prestamista (force-placed insurance) lo contrata el administrador hipotecario cuando falta el seguro requerido o su comprobante. Protege el interés del prestamista y no sustituye una revisión completa de pertenencias o responsabilidad. Pídanos comparar condiciones de reemplazo y enviar constancia al administrador. Confirme cobertura realmente vigente, fecha y recepción del documento antes de dar el asunto por resuelto."] },
    ] },
  },
  "high-value-home-insurance-underwriting-california": {
    sources: [residential],
    en: { limits: "Document the home's actual construction and ownership. An accepted application or completed inspection does not promise unlimited reconstruction coverage.", sections: [
      { heading: "Explain what an address cannot tell an underwriter", paragraphs: ["Underwriting is the insurer's evaluation of whether to accept a risk and what terms to offer. Hypothetical example: two homes have the same square footage, but one has imported stone, custom cabinetry, and difficult hillside access. A basic estimate that treats them alike can miss meaningful rebuilding costs. Provide plans, photographs, and renovation invoices rather than relying only on the sales appraisal.", "A trust or company on the property title also raises an insured-name question. Listing the family as residents does not automatically protect every ownership interest. Ask us to check the title information with the policy's named-insured and additional-interest provisions, without changing ownership documents."] },
      { heading: "Make the submission useful, not just large", paragraphs: ["Organize documents by roof, systems, custom features, detached structures, and mitigation work. Explain dates and any mismatch with public records. Then ask which facts affect eligibility and which affect the coverage amount: a leak shutoff system can influence the application, but it does not establish the water-damage limit. A stronger submission gives the insurer accurate facts; it does not guarantee acceptance or a particular price."] },
    ] },
    es: { limits: "Documente construcción y titularidad reales. Una solicitud aceptada o una inspección terminada no promete reconstrucción ilimitada.", sections: [
      { heading: "Explique lo que una dirección no revela", paragraphs: ["La suscripción (underwriting) es la evaluación de la aseguradora para aceptar un riesgo y ofrecer condiciones. Ejemplo hipotético: dos casas tienen la misma superficie, pero una incluye piedra importada, gabinetes personalizados y acceso difícil en pendiente. Un cálculo básico que las trate igual puede omitir costos importantes. Entregue planos, fotos y facturas, no solo la tasación de venta.", "Un fideicomiso o una empresa en el título también plantea quién debe quedar asegurado. Registrar a la familia como residente no protege automáticamente todos los intereses de propiedad. Pídanos comparar el título con los asegurados nombrados e intereses adicionales de la póliza, sin modificar documentos de titularidad."] },
      { heading: "Prepare un expediente útil, no solo voluminoso", paragraphs: ["Organice documentos por techo, sistemas, características personalizadas, estructuras separadas y mitigación. Explique fechas y diferencias con registros públicos. Pregunte qué afecta la elegibilidad y qué afecta el monto asegurado: un cierre automático de agua puede influir en la solicitud, pero no establece el límite de daños por agua. Un expediente sólido aporta hechos correctos; no garantiza aceptación ni precio."] },
    ] },
  },
  "insuring-jewelry-art-collections": {
    sources: [residential],
    en: { limits: "Read the limit for the item and the particular cause of loss. An appraisal supports value; it does not override a policy exclusion or establish automatic agreed-value coverage.", sections: [
      { heading: "A large belongings limit can still leave a small jewelry limit", paragraphs: ["Illustrative example: a policy has $100,000 of personal-property coverage but a $1,500 jewelry-theft limit. A stolen $6,000 ring would face that $1,500 ceiling before considering the applicable deductible and other conditions. The larger total belongings limit does not remove the category restriction. These figures are examples, not standard limits for every policy.", "Scheduling means identifying an item on a coverage list through an endorsement or separate policy. Ask whether the scheduled protection covers accidental loss or disappearance as well as theft. A ring lost while traveling raises a different question from a ring stolen during a documented burglary."] },
      { heading: "Agree on how value will be measured", paragraphs: ["Agreed value, stated amount, replacement cost, and actual cash value are not interchangeable promises. Ask whether the insurer will pay an agreed figure, replace the item, repair it, or apply depreciation—and what the contract allows if its value has changed. Bring recent appraisals, receipts, identifying details, and photographs. Have us check travel, storage, transit, restoration, and newly purchased items before assuming they are included."] },
    ] },
    es: { limits: "Lea el límite del objeto y de la causa de pérdida. Una tasación respalda valor, pero no elimina exclusiones ni establece automáticamente cobertura a valor acordado.", sections: [
      { heading: "Un límite grande de pertenencias puede esconder uno pequeño de joyería", paragraphs: ["Ejemplo ilustrativo: hay $100,000 para bienes personales, pero solo $1,500 por robo de joyas. Un anillo robado de $6,000 enfrentaría ese máximo de $1,500 antes de considerar deducible y otras condiciones. El total mayor no elimina la restricción de categoría. Son cifras de ejemplo, no límites estándar de toda póliza.", "Programar significa identificar el objeto en una lista de cobertura mediante endoso o póliza separada. Pregunte si incluye pérdida accidental o desaparición además de robo. Perder un anillo de viaje plantea otra pregunta que un robo documentado durante una entrada forzada."] },
      { heading: "Confirme cómo se determinará el valor", paragraphs: ["Valor acordado, cantidad declarada, costo de reemplazo y valor real en efectivo no prometen lo mismo. Pregunte si la aseguradora pagará una cifra acordada, reemplazará, reparará o descontará depreciación, y qué permite el contrato si cambió el valor. Traiga tasaciones recientes, recibos, identificaciones y fotos. Pídanos revisar viajes, almacenamiento, transporte, restauración y compras nuevas antes de suponer que están incluidos."] },
    ] },
  },
};
