// The five risk topics appear in the same order in each existing location guide.
export const locationGuidance = {
  en: [
    "Check the exact property, not just the city name. Ask which roof, vent, vegetation, and access details the insurer needs. If traditional coverage is unavailable, compare FAIR Plan fire coverage with a separate Difference in Conditions (DIC) policy for specified non-fire protections. Confirm what pays for repairs, belongings, and temporary housing under each contract.",
    "Earthquake coverage is a separate review from a typical home or property policy. Liquefaction means some water-saturated soils lose strength during shaking; a hazard map is not a guarantee of how a building will perform. Ask for the deductible in dollars, the selected belongings and temporary-living limits, and whether ground movement is covered under the proposed contract.",
    "A broken indoor pipe, a backed-up drain, and floodwater entering from outside are different insurance questions. Review the exact parcel in FEMA's flood maps, including locations outside high-risk zones. Compare National Flood Insurance Program (NFIP) or private flood coverage, building and contents limits, and the effective date. Do not assume temporary-living expenses or business income are included; NFIP does not provide those benefits.",
    "Report where the car actually spends the night, its annual mileage, drivers, and use. Uninsured/underinsured motorist bodily-injury coverage addresses covered injuries involving a responsible driver without enough insurance; it is not automatically protection for your car. Ask about collision, uninsured-motorist property damage, and any deductible waiver separately, especially for a hit-and-run.",
    "A covered fire that makes a rental uninhabitable is different from a tenant not paying rent. Compare loss-of-rents protection, rebuilding cost, and liability for covered injury or damage claims. Ordinary eviction expenses and every tenant dispute are not automatically insured. Keep maintenance and lease records, and use qualified legal guidance for landlord-tenant obligations.",
  ],
  es: [
    "Revise la propiedad exacta, no solo la ciudad. Pregunte qué datos de techo, ventilaciones, vegetación y acceso exige la aseguradora. Si no hay cobertura tradicional, compare incendio FAIR Plan con una póliza separada de diferencia en condiciones (DIC) para protecciones específicas ajenas al incendio. Confirme cuál paga reparaciones, pertenencias y vivienda temporal bajo cada contrato.",
    "El seguro sísmico requiere revisión separada de una póliza típica de casa o propiedad. Licuefacción significa que ciertos suelos saturados de agua pierden resistencia durante un sismo; un mapa no garantiza el comportamiento de un edificio. Pida el deducible en dólares, límites elegidos para pertenencias y vivienda temporal y confirme qué movimiento del terreno cubre el contrato propuesto.",
    "Una tubería interior rota, un drenaje que se devuelve y agua de inundación que entra desde afuera plantean preguntas distintas. Revise la parcela en mapas FEMA, incluso fuera de zonas de alto riesgo. Compare el Programa Nacional de Seguro contra Inundaciones (NFIP) o cobertura privada, límites de edificio y contenido y fecha de vigencia. No suponga que incluyen vivienda temporal o ingresos comerciales; NFIP no brinda esos beneficios.",
    "Informe dónde pasa la noche el auto, millaje anual, conductores y uso. La cobertura por lesiones de conductor sin seguro o con seguro insuficiente atiende lesiones cubiertas cuando el responsable no tiene suficiente seguro; no protege automáticamente su auto. Pregunte por colisión, daños materiales por conductor sin seguro y cualquier exención de deducible por separado, especialmente ante un choque con fuga.",
    "Un incendio cubierto que deja inhabitable un alquiler no es lo mismo que un inquilino que no paga. Compare pérdida de rentas, reconstrucción y responsabilidad por lesiones o daños cubiertos. Los gastos ordinarios de desalojo y toda disputa con inquilinos no quedan asegurados automáticamente. Conserve registros de mantenimiento y contratos y busque orientación legal calificada para sus obligaciones.",
  ],
};
