import Image from "next/image";
import Link from "next/link";
import { CTA, PageHero } from "@/components/ui";
import { siteConfig } from "@/lib/site-config";
export const metadata={title:"Our Agency",description:"Meet Abraham Nunez-Chavez, Abel Duran, Devan Wright, and the Abel Duran Insurance Agency service team.",alternates:{canonical:"/about"}};
const team=[
  {name:"Abel Duran",role:"Farmers Insurance Agent · Principal Agent",license:"CA Lic. No. 0F17442 · Agency Lic. No. 0K15422",copy:"Abel is the principal agent and owner of Abel Duran Insurance Agency, Inc. He provides English and Spanish service and helps individuals, families, property owners, and businesses understand personal, commercial, and life insurance options.",href:"/abel-duran",cta:"Meet Abel"},
  {name:"Devan Wright",role:"Agent / Broker · Yorba Linda",license:"CA Lic. No. 0H19544",copy:"Devan serves clients through the Yorba Linda office, with a focus on home, auto, life, landlord, commercial, marine, off-road, trailer, umbrella, and earthquake insurance.",href:"/devan-wright",cta:"Meet Devan"},
  {name:"Rashel Dominguez",role:"Service Representative",license:"Customer service and policy support",copy:"Rashel assists existing clients with policy questions, documents, billing guidance, renewals, and service requests.",href:"/customer-service",cta:"Get policy support"},
  {name:"Suzee Cervantes",role:"Service Representative",license:"Customer service and policy support",copy:"Suzee helps clients navigate policy documents, account questions, billing guidance, and policy-service requests.",href:"/customer-service",cta:"Get policy support"},
];
export default function Page(){return <><PageHero eyebrow="Our agency" title="Local guidance backed by a connected agency team.">Abraham remains your primary website contact, with direct access to experienced agents and dedicated policy-service support at two Southern California offices.</PageHero><section className="section"><div className="shell profile-layout"><div className="photo-frame portrait-frame"><Image src="/images/abraham-headshot.jpg" alt="Abraham Nunez-Chavez, California insurance agent and broker" fill sizes="(max-width: 760px) 75vw, 340px" priority /></div><div><p className="eyebrow">Primary website contact</p><h2>Abraham Nunez-Chavez</h2><p><strong>Insurance Agent/Broker · CA Lic. No. {siteConfig.license}</strong></p><p>Abraham is a licensed insurance producer affiliated with the Office of Abel Duran. He helps clients compare practical coverage options for personal, commercial, life, escrow, wildfire, and difficult-to-insure property needs.</p><p>Abraham and Abel are individually licensed insurance professionals working through Abel Duran Insurance Agency, Inc. Additional carrier options may be available when appropriate; those insurers are separate from Farmers Insurance.</p><div className="button-row"><Link className="button" href="/contact?agent=abraham">Request a quote with Abraham</Link><a className="button button-secondary" href={siteConfig.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div></section><section className="section soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Meet the team</p><h2>Agents and policy-support specialists.</h2></div><p>New-business requests and existing-policy service follow separate paths so you reach the right person quickly.</p></div><div className="team-grid">{team.map(member=><article className="team-card" key={member.name}><div className="initial-avatar" aria-hidden="true">{member.name.split(" ").map(n=>n[0]).join("")}</div><p className="eyebrow">{member.role}</p><h3>{member.name}</h3><strong>{member.license}</strong><p>{member.copy}</p><Link className="text-link" href={member.href}>{member.cta} →</Link></article>)}</div></div></section><CTA/></>}
