import Link from "next/link";
import Image from "next/image";
import { Cards, CTA } from "@/components/ui";

export const metadata = {
  title: "Insurance Agent & Broker in Moreno Valley, CA",
  description: "Personal, commercial, wildfire, life, and escrow insurance support for Moreno Valley, Riverside County, Yorba Linda, and Orange County.",
  alternates: { canonical: "/", languages: { "en-US": "/", "es-US": "/es", "x-default": "/" } },
};

const services = [
  { title: "Home & Property", text: "Learn how dwelling, belongings, liability, loss of use, deductibles, and replacement cost work together." },
  { title: "Auto & Umbrella", text: "Understand liability, uninsured motorists, physical damage, and added protection for serious claims." },
  { title: "Business Insurance", text: "Review liability, property, workers’ compensation, commercial auto, contracts, and audit exposure." },
  { title: "Life Insurance", text: "Explore coverage designed to replace income, address debts, and protect the people who depend on you." },
  { title: "Escrow Support", text: "Get responsive quotes, lender-ready documents, and help with challenging or wildfire-exposed properties." },
  { title: "Carrier Options", text: "Review Farmers Insurance products and additional brokerage markets when appropriate for the risk." },
] as const;

export default function Home() {
  return <>
    <section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">Agent/Brokers Located in Yorba Linda and Moreno Valley, Proudly Serving California</p><h1>Personal and business insurance for Riverside and Orange Counties.</h1><p className="lead">Compare Farmers Insurance solutions and additional brokerage markets with clear guidance from a licensed local agent serving Moreno Valley, Yorba Linda, and surrounding Southern California communities.</p><div className="button-row"><Link className="button" href="/contact">Start a Fast Quote</Link></div><div className="trust-line"><span>CA Lic. No. 4357305</span><span>Moreno Valley & Yorba Linda</span></div></div><aside className="hero-panel"><p className="eyebrow">Agency owner and principal agent</p><h2>Local leadership. Broader insurance support.</h2><ul><li>Farmers Insurance agency leadership</li><li>Personal, commercial, and life insurance</li><li>Support from the Moreno Valley and Yorba Linda offices</li><li>Access to additional brokerage markets when appropriate</li></ul><Link href="/abel-duran" aria-label="Meet Abel Duran">Meet Abel <span>→</span></Link></aside></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Insurance agent and broker services</p><h2>Education, coverage, and quote options.</h2></div><p>Learn what each policy protects, where common gaps develop, and how limits and deductibles affect a claim.</p></div><Cards items={services} /></div></section>
    <section className="section soft"><div className="shell photo-story"><div className="photo-frame photo-frame-wide"><Image src="/images/moreno-valley-front-desk.jpg" alt="Front desk at the Farmers Insurance office in Moreno Valley" fill sizes="(max-width: 900px) 100vw, 55vw" /></div><div><p className="eyebrow">Local, accessible service</p><h2>Insurance Agent/Broker Offices in Yorba Linda and Moreno Valley.</h2><p className="agency-attribution">Powered by the Abel Duran Insurance Agency, Inc.</p><p className="lead-small">Choose a licensed agent for quote and coverage guidance at either Southern California office. Existing-policy support is also available from the agency’s dedicated service team.</p><div className="profile-links"><Link className="text-link" href="/moreno-valley-office">Meet the Moreno Valley team →</Link><Link className="text-link" href="/yorba-linda-office">Meet the Yorba Linda team →</Link></div></div></div></section>
    <section className="section local-paths-section" id="service-areas"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Local insurance support</p><h2>Coverage guidance across Riverside and Orange Counties.</h2></div><p>Choose the service area closest to you for local property, business, wildfire, earthquake, and escrow considerations.</p></div><div className="location-links"><Link href="/locations/moreno-valley"><strong>Moreno Valley</strong><span>Primary office and local insurance support →</span></Link><Link href="/locations/riverside-county"><strong>Riverside County</strong><span>Personal, commercial, wildfire, and escrow insurance →</span></Link><Link href="/locations/yorba-linda"><strong>Yorba Linda</strong><span>Home, auto, umbrella, business, and catastrophe reviews →</span></Link><Link href="/locations/orange-county"><strong>Orange County</strong><span>Personal, commercial, life, and real-estate support →</span></Link></div></div></section>
    <section className="section quick-coverage soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Choose coverage</p><h2>Start with what you need to protect.</h2></div><Link className="text-link" href="/contact">Not sure? Start a two-step request →</Link></div><div className="quick-path-grid"><Link href="/insurance/homeowners-insurance">Homeowners</Link><Link href="/insurance/auto-insurance">Auto</Link><Link href="/insurance/landlord-insurance">Landlord</Link><Link href="/insurance/general-liability-insurance">General Liability</Link><Link href="/insurance/workers-compensation-insurance">Workers’ Compensation</Link><Link href="/insurance/commercial-auto-insurance">Commercial Auto</Link></div></div></section>
    <section className="section risk-context"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Risk in context</p><h2>A few numbers worth understanding.</h2></div><p>Useful benchmarks can make insurance decisions less abstract. Your actual risk and coverage will depend on your property, policy, and carrier.</p></div><div className="stat-cards"><article><strong>$25,000</strong><p>Approximate damage that just one inch of floodwater can cause to a home.</p><a href="https://agents.floodsmart.gov/sites/default/files/media/document/2025-07/fema-nfip-just-one-inch-of-floodwater-flyer-06-2023.pdf" target="_blank" rel="noreferrer">FEMA / NFIP source ↗</a></article><article><strong>40%+</strong><p>Share of NFIP flood claims that come from outside high-risk flood areas.</p><a href="https://agents.floodsmart.gov/sites/default/files/media/document/2025-07/fema-nfip-everyone-needs-flood-insurance-fact-sheet-05-2023.pdf" target="_blank" rel="noreferrer">FEMA / NFIP source ↗</a></article><article><strong>Nearly ⅔</strong><p>California residential earthquake policies provided by the California Earthquake Authority.</p><a href="https://www.earthquakeauthority.com/about-cea/financials/cea-financial-strength" target="_blank" rel="noreferrer">CEA source ↗</a></article></div><p className="source-note">Statistics are educational and do not describe or guarantee coverage under any policy.</p></div></section>
    <section className="section split-section"><div className="shell split"><div><p className="eyebrow">For real estate professionals</p><h2>Keep insurance from becoming a last-minute escrow problem.</h2><p className="lead-small">Early review can identify wildfire exposure, claims-history concerns, reconstruction questions, or underwriting requirements before they affect closing.</p><Link className="text-link" href="/referral-partners">Explore partner support →</Link></div><div className="stat-list"><div><strong>Responsive</strong><span>quote and documentation support</span></div><div><strong>Clear</strong><span>buyer and lender communication</span></div><div><strong>Continued</strong><span>service after escrow closes</span></div></div></div></section>
    <section className="section"><div className="shell section-heading"><div><p className="eyebrow">Education center</p><h2>Make coverage decisions with context.</h2></div><Link className="text-link" href="/education">View all resources →</Link></div><div className="shell feature-links"><Link href="/education/fair-plan-dic"><span>Wildfire properties</span><strong>California FAIR Plan and DIC Coverage Explained</strong></Link><Link href="/education/replacement-cost-market-value"><span>Home insurance</span><strong>Replacement Cost vs. Market Value</strong></Link><Link href="/education/insurance-before-escrow"><span>Real estate</span><strong>What Realtors Should Know Before Escrow</strong></Link></div></section>
    <CTA />
  </>;
}
