"use client";
import { FormEvent, useState } from "react";

const reps={first:["Rashel and Suzee","rashel.aduran@farmersagency.com,suzee.aduran@farmersagency.com"],rashel:["Rashel Dominguez","rashel.aduran@farmersagency.com"],suzee:["Suzee Cervantes","suzee.aduran@farmersagency.com"]} as const;

export function ServiceRequestForm({locale="en"}:{locale?:"en"|"es"}){
  const es=locale==="es";
  const [ready,setReady]=useState<{email:string;gmail:string}|null>(null);
  function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault(); const data=Object.fromEntries(new FormData(e.currentTarget)); if(data.website)return;
    const rep=reps[data.representative as keyof typeof reps]||reps.first;
    const subject=es?`Solicitud de servicio de póliza - ${String(data.fullName)}`:`Policy service request - ${String(data.fullName)}`;
    const body=(es?["Hola, equipo de servicio de la agencia:","",`Representante preferido: ${rep[0]}`,`Nombre: ${data.fullName}`,`Correo electrónico: ${data.email}`,`Teléfono: ${data.phone}`,`Contacto preferido: ${data.contactMethod}`,`Número de póliza: ${data.policyNumber||"No proporcionado"}`,`Tipo de seguro: ${data.insuranceType}`,`Tipo de solicitud: ${data.requestType}`,`Oficina preferida: ${data.office}`,`Fecha de vigencia solicitada: ${data.effectiveDate||"No proporcionada"}`,"","Detalles de la solicitud:",String(data.description),"","Entiendo que este envío no obliga, cambia, restablece ni cancela cobertura."]:["Hello Agency Service Team,","",`Preferred representative: ${rep[0]}`,`Name: ${data.fullName}`,`Email: ${data.email}`,`Phone: ${data.phone}`,`Preferred contact: ${data.contactMethod}`,`Policy number: ${data.policyNumber||"Not provided"}`,`Insurance type: ${data.insuranceType}`,`Request type: ${data.requestType}`,`Preferred office: ${data.office}`,`Requested effective date: ${data.effectiveDate||"Not provided"}`,"","Request details:",String(data.description),"","I understand this submission does not bind, change, reinstate, or cancel coverage."]).join("\n");
    setReady({email:`mailto:${rep[1]}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,gmail:`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(rep[1])}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
  }
  const t=es?{ready:"Su solicitud de servicio está lista.",readyText:"Seleccione una opción de correo y presione Enviar. La cobertura no se ha modificado a menos que reciba confirmación.",gmail:"Abrir Gmail",other:"Otra aplicación de correo",name:"Nombre completo",email:"Correo electrónico",phone:"Teléfono",contact:"Contacto preferido",policy:"Número de póliza",optional:"(opcional)",insurance:"Tipo de seguro",request:"Tipo de solicitud",representative:"Representante preferido",office:"Oficina preferida",date:"Fecha de vigencia solicitada",applicable:"(si corresponde)",description:"Descripción de la solicitud",submit:"Enviar solicitud de servicio",disclosure:"Enviar este formulario no obliga, cambia, restablece ni cancela cobertura de seguro. Las solicitudes de cobertura no entran en vigor hasta que las confirme un profesional de seguros con licencia o la aseguradora correspondiente. No envíe números de Seguro Social, información de tarjetas de pago, datos bancarios, contraseñas ni otra información confidencial."}:{ready:"Your service request is ready.",readyText:"Select an email option and press Send. Coverage has not been changed unless you receive confirmation.",gmail:"Open Gmail",other:"Other Email App",name:"Full name",email:"Email",phone:"Phone",contact:"Preferred contact",policy:"Policy number",optional:"(optional)",insurance:"Type of insurance",request:"Type of request",representative:"Preferred representative",office:"Preferred office",date:"Requested effective date",applicable:"(if applicable)",description:"Description of request",submit:"Submit Service Request",disclosure:"Submitting this form does not bind, change, reinstate, or cancel insurance coverage. Coverage requests are not effective until confirmed by a licensed insurance professional or the applicable insurance carrier. Please do not submit Social Security numbers, payment-card information, banking information, passwords, or other sensitive information."};
  const insurance=es?["Auto","Casa","Inquilinos o condominio","Arrendador","Vida","Negocio o comercial","Otro"]:["Auto","Home","Renters or condo","Landlord","Life","Business or commercial","Other"];
  const requests=es?["Facturación o pago","Comprobante de seguro o tarjetas de identificación","Actualización de prestamista o acreedor hipotecario","Agregar o eliminar un vehículo","Agregar o eliminar un conductor","Cambio de dirección","Pregunta sobre cobertura","Cambio de póliza","Pregunta sobre renovación","Solicitud de cancelación","Asistencia con reclamos","Solicitud de documentos","Otro"]:["Billing or payment","Proof of insurance or ID cards","Lender or mortgagee update","Add or remove a vehicle","Add or remove a driver","Address change","Coverage question","Policy change","Renewal question","Cancellation request","Claims assistance","Document request","Other"];
  return <form className="quote-form quote-step" onSubmit={submit}><div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1}/></label></div>{ready?<section className="quote-ready"><div className="ready-mark">✓</div><h2>{t.ready}</h2><p>{t.readyText}</p><div className="contact-action-panel"><a className="button" href={ready.gmail} target="_blank" rel="noreferrer">{t.gmail}</a><a className="button button-secondary" href={ready.email}>{t.other}</a><a className="button button-secondary" href="tel:+19516538888">{es?"Llamar al":"Call"} 951-653-8888</a></div></section>:<><div className="form-grid"><label>{t.name}<input name="fullName" required autoComplete="name"/></label><label>{t.email}<input name="email" required type="email" autoComplete="email"/></label><label>{t.phone}<input name="phone" required type="tel" autoComplete="tel"/></label><label>{t.contact}<select name="contactMethod">{(es?["Teléfono","Correo electrónico","Mensaje de texto"]:["Phone","Email","Text"]).map(x=><option key={x}>{x}</option>)}</select></label><label>{t.policy} <span>{t.optional}</span><input name="policyNumber"/></label><label>{t.insurance}<select name="insuranceType" required>{insurance.map(x=><option key={x}>{x}</option>)}</select></label><label>{t.request}<select name="requestType" required>{requests.map(x=><option key={x}>{x}</option>)}</select></label><label>{t.representative}<select name="representative"><option value="first">{es?"Primera representante disponible":"First available representative"}</option><option value="rashel">Rashel Dominguez</option><option value="suzee">Suzee Cervantes</option></select></label><label>{t.office}<select name="office"><option>{es?"Sin preferencia":"No preference"}</option><option>Moreno Valley</option><option>Yorba Linda</option></select></label><label>{t.date} <span>{t.applicable}</span><input name="effectiveDate" type="date"/></label></div><label>{t.description}<textarea name="description" required rows={5}/></label><p className="service-disclosure">{t.disclosure}</p><button className="button" type="submit">{t.submit}</button></>}</form>;
}
