import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CTA, PageHero } from "@/components/ui";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "About Abel Duran | Farmers Insurance Agent and Agency Owner",
  description: "Meet Abel Duran, owner and principal agent of Abel Duran Insurance Agency, serving Moreno Valley, Yorba Linda, and Southern California. CA Lic. 0F17442.",
  alternates: { canonical: "/abel-duran" },
};

const insuranceServices = ["Auto", "Homeowners", "Renters and condo", "Landlord", "Umbrella", "Life", "Business", "Commercial auto", "Commercial property", "General liability", "Workers’ compensation"];

export default function Page() {
  const schema = { "@context": "https://schema.org", "@type": "Person", name: "Abel Duran", image: `${siteConfig.url}/images/abel-duran.jpg`, jobTitle: "Owner and Principal Farmers Insurance Agent", worksFor: { "@type": "InsuranceAgency", name: "Abel Duran Insurance Agency, Inc.", identifier: "California Agency License No. 0K15422" }, telephone: "+1-951-653-8888", email: "Aduran@farmersagent.com", address: { "@type": "PostalAddress", streetAddress: "13800 Heacock St., Suite C120", addressLocality: "Moreno Valley", addressRegion: "CA", postalCode: "92553", addressCountry: "US" }, areaServed: ["Moreno Valley", "Yorba Linda", "Riverside County", "Orange County", "San Bernardino County", "Inland Empire", "Southern California"], knowsLanguage: ["English", "Spanish"], url: `${siteConfig.url}/abel-duran`, sameAs: ["https://agents.farmers.com/ca/moreno-valley/abel-duran/"], description: "California Insurance License No. 0F17442. Owner and principal agent of Abel Duran Insurance Agency, Inc., California Agency License No. 0K15422." };
  return <><PageHero eyebrow="About Abel Duran" title="Experience, local leadership, and practical insurance guidance.">Abel Duran is the owner and principal agent of Abel Duran Insurance Agency, serving clients through the Moreno Valley and Yorba Linda offices.</PageHero>
    <section className="section"><div className="shell abel-intro"><div className="abel-portrait"><Image src="/images/abel-duran.jpg" alt="Abel Duran, owner and principal agent of Abel Duran Insurance Agency" fill sizes="(max-width: 760px) 85vw, 420px" priority /></div><div><p className="eyebrow">Farmers Insurance Agent · Agency Owner</p><h2>Abel Duran</h2><p><strong>Individual CA Lic. No. 0F17442<br/>Agency CA Lic. No. 0K15422</strong></p><p>Abel is an experienced Farmers Insurance agent and the owner and principal agent of Abel Duran Insurance Agency, Inc. He has been appointed with Farmers for more than a decade and has served the Moreno Valley community since approximately 2006.</p><p>His approach centers on personalized guidance, clear coverage explanations, and long-term client service. Abel helps individuals, families, property owners, and businesses understand available options and select protection based on their needs.</p><p>Service is available in English and Spanish throughout Riverside County, Orange County, San Bernardino County, the Inland Empire, and surrounding Southern California communities.</p><div className="button-row"><Link className="button" href="/contact?agent=abel">Request a Quote With Abel</Link><a className="button button-secondary" href="tel:+19516538888">Call 951-653-8888</a><a className="button button-secondary" href="mailto:Aduran@farmersagent.com">Email Abel</a></div></div></div></section>
    <section className="section soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Insurance solutions</p><h2>Personal, commercial, and life insurance.</h2></div><p>Coverage and carrier availability vary based on eligibility, underwriting, location, and selected limits.</p></div><div className="specialty-grid">{insuranceServices.map(item=><span key={item}>{item} insurance</span>)}</div></div></section>
    <section className="section"><div className="shell about-abel-details"><div><p className="eyebrow">Professional background</p><h2>Leading a two-office agency team.</h2><p>Abel owns and leads both agency locations, coordinating with individually licensed agents and dedicated service specialists so clients have clear paths for new quotes and existing-policy support.</p><div className="recognition-list"><p><strong>More than 10 years</strong><span>Appointed with Farmers Insurance</span></p><p><strong>English and Spanish</strong><span>Bilingual insurance guidance</span></p><p><strong>CSP certification</strong><span>Professional Farmers certification</span></p><p><strong>Century Club</strong><span>Farmers recognition</span></p></div></div><aside className="details-card"><h2>Agency relationship</h2><p>Abraham Nunez-Chavez is a licensed insurance producer affiliated with the Office of Abel Duran. Abraham and Abel are individually licensed insurance professionals working through Abel Duran Insurance Agency, Inc.</p><p>Additional carrier options may be available when appropriate. Non-Farmers carriers are separate insurers and are not affiliated with Farmers Insurance.</p><Link className="text-link" href="/about">Meet the full agency team →</Link></aside></div></section>
    <section className="section navy-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Office locations</p><h2>Meet with Abel’s agency team.</h2></div><p>Choose the office most convenient for you.</p></div><div className="abel-office-grid"><article><h3>Moreno Valley</h3><p>{siteConfig.morenoValleyOffice}</p><p><a href="tel:+19516538888">951-653-8888</a></p><a className="text-link" href="https://maps.google.com/?q=13800+Heacock+St+Suite+C120+Moreno+Valley+CA+92553" target="_blank" rel="noreferrer">Get directions ↗</a></article><article><h3>Yorba Linda</h3><p>{siteConfig.yorbaLindaOffice}</p><p><a href="tel:+17147016411">714-701-6411</a></p><Link className="text-link" href="/yorba-linda-office">Meet the Yorba Linda team →</Link><a className="text-link" href="https://maps.google.com/?q=23621+La+Palma+Ave+Suite+A+Yorba+Linda+CA+92887" target="_blank" rel="noreferrer">Get directions ↗</a></article></div><div className="button-row"><a className="button button-light" href="https://agents.farmers.com/ca/moreno-valley/abel-duran/" target="_blank" rel="noreferrer">View Abel’s Official Farmers Profile ↗</a></div></div></section>
    <CTA/><script id="abel-schema" type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>;
}
