import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/ui";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = { title: "Yorba Linda Insurance Office | Abel Duran Insurance Agency", description: "Meet Abel Duran, Devan Wright, and Emily Lussier at the Yorba Linda office of Abel Duran Insurance Agency. Call 714-701-6411.", alternates: { canonical: "/yorba-linda-office" } };
const specialties = ["Life", "Homeowners", "Landlord and renters", "Auto", "Commercial", "Marine", "Off-road vehicles", "Trailers", "Umbrella", "Earthquake"];

export default function YorbaLindaOfficePage() {
  const schema = { "@context": "https://schema.org", "@type": "InsuranceAgency", name: "Abel Duran Insurance Agency — Yorba Linda", url: `${siteConfig.url}/yorba-linda-office`, telephone: "+1-714-701-6411", email: "emily.aduran@farmersagency.com", address: { "@type": "PostalAddress", streetAddress: "23621 La Palma Ave., Suite A", addressLocality: "Yorba Linda", addressRegion: "CA", postalCode: "92887", addressCountry: "US" }, parentOrganization: { "@type": "InsuranceAgency", name: "Abel Duran Insurance Agency, Inc.", identifier: "California Agency License No. 0K15422" }, employee: [{ "@type": "Person", name: "Abel Duran", jobTitle: "Owner and Principal Agent", identifier: "California Insurance License No. 0F17442" }, { "@type": "Person", name: "Devan Wright", jobTitle: "Insurance Agent and Broker", identifier: "California Insurance License No. 0H19544" }, { "@type": "Person", name: "Emily Lussier", jobTitle: "Customer Service Representative", sameAs: "https://www.linkedin.com/in/emily-lussier/" }] };
  return <><PageHero eyebrow="Yorba Linda office" title="Local insurance guidance and policy support in Yorba Linda.">Meet the Abel Duran Insurance Agency team serving Orange County from 23621 La Palma Avenue, Suite A.</PageHero>
    <section className="office-gallery" aria-label="Yorba Linda office exterior"><div className="shell office-gallery-grid"><div><Image src="/images/yorba-linda-office-front.jpg" alt="Front entrance of the Yorba Linda Farmers Insurance office at 23621 La Palma Avenue" fill sizes="(max-width: 760px) 100vw, 58vw" priority /></div><div><Image src="/images/yorba-linda-office-wide.jpg" alt="Wide exterior view and parking area of the Yorba Linda insurance office" fill sizes="(max-width: 760px) 100vw, 42vw" /></div></div></section>
    <section className="section"><div className="shell office-summary"><div><p className="eyebrow">One agency · Two locations</p><h2>Owned and led by Abel Duran.</h2><p>Abel Duran owns and serves as principal agent for both the Yorba Linda and Moreno Valley offices of Abel Duran Insurance Agency. The Yorba Linda team provides new-business guidance and existing-policy support from one local office.</p><div className="button-row"><a className="button" href="tel:+17147016411">Call 714-701-6411</a><a className="button button-secondary" href="https://maps.google.com/?q=23621+La+Palma+Ave+Suite+A+Yorba+Linda+CA+92887" target="_blank" rel="noreferrer">Get Directions ↗</a></div></div><aside className="details-card"><h2>Office details</h2><dl><dt>Address</dt><dd>{siteConfig.yorbaLindaOffice}</dd><dt>Main office</dt><dd><a href="tel:+17147016411">714-701-6411</a></dd><dt>Fax</dt><dd>714-694-7159</dd><dt>Second location</dt><dd>{siteConfig.morenoValleyOffice} · <a href="tel:+19516538888">951-653-8888</a></dd></dl></aside></div></section>
    <section className="section soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Yorba Linda team</p><h2>Agents and customer service.</h2></div><p>Choose the right contact for a new quote, coverage guidance, or help servicing an existing policy.</p></div><div className="location-team-grid">
      <article className="location-profile"><div className="location-profile-photo"><Image src="/images/abel-duran.jpg" alt="Abel Duran, owner and principal agent of Abel Duran Insurance Agency" fill sizes="(max-width: 760px) 100vw, 33vw" priority /></div><div><p className="eyebrow">Owner and principal agent</p><h2>Abel Duran</h2><p><strong>CA Lic. No. 0F17442</strong></p><p>Abel owns and leads both agency locations and assists clients with personal, commercial, and life insurance.</p><div className="profile-links"><Link className="text-link" href="/abel-duran">View Abel’s profile →</Link><Link className="text-link" href="/contact?agent=abel">Request a quote with Abel →</Link></div></div></article>
      <article className="location-profile"><div className="location-profile-placeholder" aria-hidden="true">DW</div><div><p className="eyebrow">Agent / Broker</p><h2>Devan Wright</h2><p><strong>CA Lic. No. 0H19544</strong></p><p>Devan provides personal, commercial, and life insurance guidance from the Yorba Linda office.</p><div className="profile-links"><Link className="text-link" href="/devan-wright">View Devan’s profile →</Link><a className="text-link" href="tel:+17147016412">Call or text 714-701-6412 →</a><a className="text-link" href="mailto:devan.aduran@farmersagency.com">Email Devan →</a></div></div></article>
      <article className="location-profile"><div className="location-profile-photo"><Image src="/images/emily-lussier.jpg" alt="Emily Lussier, customer service representative at the Yorba Linda office" fill sizes="(max-width: 760px) 100vw, 33vw" /></div><div><p className="eyebrow">Customer Service Representative</p><h2>Emily Lussier</h2><p>Emily assists Yorba Linda clients with policy questions, documents, billing guidance, renewals, and general account support.</p><div className="profile-links"><a className="text-link" href="mailto:emily.aduran@farmersagency.com">Email Emily →</a><a className="text-link" href="tel:+17147016411">Call 714-701-6411 →</a><a className="text-link" href="https://www.linkedin.com/in/emily-lussier/" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></div></div></article>
    </div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Local coverage intelligence</p><h2>Yorba Linda and Orange County risk guides.</h2></div><p>Review official wildfire, earthquake, flood, auto-rating, and landlord resources before requesting coverage.</p></div><div className="location-links"><Link href="/locations/yorba-linda"><strong>Yorba Linda risk guide</strong><span>City-specific hazards, insurance impacts, and official resources →</span></Link><Link href="/locations/orange-county"><strong>Orange County risk guide</strong><span>Countywide wildfire, earthquake, flood, auto, and landlord considerations →</span></Link></div></div></section>
    <section className="section soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Coverage options</p><h2>Personal, commercial, specialty, and life insurance.</h2></div><p>Availability varies by carrier, eligibility, underwriting, and coverage selection.</p></div><div className="specialty-grid">{specialties.map(item => <span key={item}>{item} insurance</span>)}</div><p className="disclaimer">Submitting a request does not bind or change coverage. Coverage is effective only after confirmation by a licensed insurance professional or applicable carrier.</p></div></section>
    <script id="yorba-linda-office-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></>;
}
